# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.

    The version of the OpenAPI document: <PINNED>
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.upload_content_out import UploadContentOut

class TestUploadContentOut(unittest.TestCase):
    """UploadContentOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadContentOut:
        """Test UploadContentOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadContentOut`
        """
        model = UploadContentOut()
        if include_optional:
            return UploadContentOut(
                checksum = agentdrive_sdk.models.upload_checksum_out.UploadChecksumOut(
                    algorithm = 'crc32c',
                    value = 'izA9LC==', ),
                media_type = '',
                size_bytes = 0.0
            )
        else:
            return UploadContentOut(
                checksum = agentdrive_sdk.models.upload_checksum_out.UploadChecksumOut(
                    algorithm = 'crc32c',
                    value = 'izA9LC==', ),
                media_type = '',
                size_bytes = 0.0,
        )
        """

    def testUploadContentOut(self):
        """Test UploadContentOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
