# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.

    The version of the OpenAPI document: <PINNED>
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.validation_error_response_error_details import ValidationErrorResponseErrorDetails

class TestValidationErrorResponseErrorDetails(unittest.TestCase):
    """ValidationErrorResponseErrorDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationErrorResponseErrorDetails:
        """Test ValidationErrorResponseErrorDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationErrorResponseErrorDetails`
        """
        model = ValidationErrorResponseErrorDetails()
        if include_optional:
            return ValidationErrorResponseErrorDetails(
                fields = [
                    agentdrive_sdk.models.validation_error_response_error_details_fields_inner.ValidationErrorResponse_error_details_fields_inner(
                        location = '',
                        reason = '', )
                    ]
            )
        else:
            return ValidationErrorResponseErrorDetails(
        )
        """

    def testValidationErrorResponseErrorDetails(self):
        """Test ValidationErrorResponseErrorDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
