# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: <PINNED>
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.grant_create_in import GrantCreateIn

class TestGrantCreateIn(unittest.TestCase):
    """GrantCreateIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GrantCreateIn:
        """Test GrantCreateIn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GrantCreateIn`
        """
        model = GrantCreateIn()
        if include_optional:
            return GrantCreateIn(
                expires_in = 56,
                principal = agentdrive_sdk.models.grant_principal_in.GrantPrincipalIn(
                    email = '',
                    id = '',
                    type = 'user', ),
                resource = '',
                role = 'viewer'
            )
        else:
            return GrantCreateIn(
                principal = agentdrive_sdk.models.grant_principal_in.GrantPrincipalIn(
                    email = '',
                    id = '',
                    type = 'user', ),
                resource = '',
                role = 'viewer',
        )
        """

    def testGrantCreateIn(self):
        """Test GrantCreateIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
