# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: <PINNED>
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.drive_read_out import DriveReadOut

class TestDriveReadOut(unittest.TestCase):
    """DriveReadOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DriveReadOut:
        """Test DriveReadOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DriveReadOut`
        """
        model = DriveReadOut()
        if include_optional:
            return DriveReadOut(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                email = '',
                etag = '',
                id = '',
                metageneration = 56,
                organization_id = '',
                storage_bytes = 56,
                storage_limit = 56
            )
        else:
            return DriveReadOut(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                etag = '',
                id = '',
                metageneration = 56,
                organization_id = '',
                storage_bytes = 56,
                storage_limit = 56,
        )
        """

    def testDriveReadOut(self):
        """Test DriveReadOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
