# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.share_mint_out import ShareMintOut

class TestShareMintOut(unittest.TestCase):
    """ShareMintOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShareMintOut:
        """Test ShareMintOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShareMintOut`
        """
        model = ShareMintOut()
        if include_optional:
            return ShareMintOut(
                id = '',
                resource_type = 'artifact',
                resource_id = '',
                role = 'viewer',
                audience = '',
                has_password = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_accessed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                access_count = 56,
                share_key = '',
                url = ''
            )
        else:
            return ShareMintOut(
                id = '',
                resource_type = 'artifact',
                resource_id = '',
                role = 'viewer',
                audience = '',
                has_password = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                share_key = '',
                url = '',
        )
        """

    def testShareMintOut(self):
        """Test ShareMintOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
