# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.grant_out import GrantOut

class TestGrantOut(unittest.TestCase):
    """GrantOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GrantOut:
        """Test GrantOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GrantOut`
        """
        model = GrantOut()
        if include_optional:
            return GrantOut(
                id = '',
                resource_type = 'artifact',
                resource_id = '',
                principal_type = 'user',
                principal_id = '',
                principal_email = '',
                role = 'viewer',
                granted_by_type = '',
                granted_by_id = '',
                on_behalf_of = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                artifacts_affected = 56
            )
        else:
            return GrantOut(
                id = '',
                resource_type = 'artifact',
                resource_id = '',
                principal_type = 'user',
                role = 'viewer',
                granted_by_type = '',
                granted_by_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testGrantOut(self):
        """Test GrantOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
