# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.

    The version of the OpenAPI document: <PINNED>
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.grant_list_out import GrantListOut

class TestGrantListOut(unittest.TestCase):
    """GrantListOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GrantListOut:
        """Test GrantListOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GrantListOut`
        """
        model = GrantListOut()
        if include_optional:
            return GrantListOut(
                items = [
                    agentdrive_sdk.models.grant_out.GrantOut(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        drive_id = 'drv_bf325375e030fccb',
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        id = 'grn_bf325375e030fccb',
                        principal_id = '',
                        principal_type = 'agent',
                        resource_id = '',
                        resource_type = 'drive',
                        revision = 'rev_bf325375e030fccb',
                        revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        role = 'viewer',
                        state = 'active', )
                    ],
                next_cursor = ''
            )
        else:
            return GrantListOut(
                items = [
                    agentdrive_sdk.models.grant_out.GrantOut(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        drive_id = 'drv_bf325375e030fccb',
                        expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        id = 'grn_bf325375e030fccb',
                        principal_id = '',
                        principal_type = 'agent',
                        resource_id = '',
                        resource_type = 'drive',
                        revision = 'rev_bf325375e030fccb',
                        revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        role = 'viewer',
                        state = 'active', )
                    ],
                next_cursor = '',
        )
        """

    def testGrantListOut(self):
        """Test GrantListOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
