# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: <PINNED>
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.compile_job_in import CompileJobIn

class TestCompileJobIn(unittest.TestCase):
    """CompileJobIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompileJobIn:
        """Test CompileJobIn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompileJobIn`
        """
        model = CompileJobIn()
        if include_optional:
            return CompileJobIn(
                options = agentdrive_sdk.models.compile_options.CompileOptions(
                    engine = '',
                    entrypoint = '',
                    wait = True, ),
                task = 'latex.compile'
            )
        else:
            return CompileJobIn(
        )
        """

    def testCompileJobIn(self):
        """Test CompileJobIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
