# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: <PINNED>
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.response_post_query_v0_query_post import ResponsePostQueryV0QueryPost

class TestResponsePostQueryV0QueryPost(unittest.TestCase):
    """ResponsePostQueryV0QueryPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponsePostQueryV0QueryPost:
        """Test ResponsePostQueryV0QueryPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponsePostQueryV0QueryPost`
        """
        model = ResponsePostQueryV0QueryPost()
        if include_optional:
            return ResponsePostQueryV0QueryPost(
                dry_run = true,
                engine = '',
                estimated_bytes_processed = 56,
                result_schema = [
                    { }
                    ],
                valid = True,
                bytes_processed = 56,
                cache_hit = True,
                preview = [
                    { }
                    ],
                result_art_id = '',
                row_count = 56
            )
        else:
            return ResponsePostQueryV0QueryPost(
                dry_run = true,
                engine = '',
                estimated_bytes_processed = 56,
                result_schema = [
                    { }
                    ],
                valid = True,
                bytes_processed = 56,
                cache_hit = True,
                preview = [
                    { }
                    ],
                result_art_id = '',
                row_count = 56,
        )
        """

    def testResponsePostQueryV0QueryPost(self):
        """Test ResponsePostQueryV0QueryPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
