# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.change_page_out import ChangePageOut

class TestChangePageOut(unittest.TestCase):
    """ChangePageOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangePageOut:
        """Test ChangePageOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangePageOut`
        """
        model = ChangePageOut()
        if include_optional:
            return ChangePageOut(
                items = [
                    agentdrive_sdk.models.change_out.ChangeOut(
                        id = 'chg_bf325375e030fccb', 
                        change_set_id = '', 
                        type = '', 
                        drive_id = 'drv_bf325375e030fccb', 
                        actor = agentdrive_sdk.models.change_actor_out.ChangeActorOut(
                            type = 'agent', 
                            id = '', ), 
                        resource = agentdrive_sdk.models.change_resource_out.ChangeResourceOut(
                            type = 'drive', 
                            id = '', ), 
                        previous_revision = '', 
                        revision = '', 
                        occurred_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        data = { }, )
                    ],
                next_cursor = '',
                has_more = True
            )
        else:
            return ChangePageOut(
                items = [
                    agentdrive_sdk.models.change_out.ChangeOut(
                        id = 'chg_bf325375e030fccb', 
                        change_set_id = '', 
                        type = '', 
                        drive_id = 'drv_bf325375e030fccb', 
                        actor = agentdrive_sdk.models.change_actor_out.ChangeActorOut(
                            type = 'agent', 
                            id = '', ), 
                        resource = agentdrive_sdk.models.change_resource_out.ChangeResourceOut(
                            type = 'drive', 
                            id = '', ), 
                        previous_revision = '', 
                        revision = '', 
                        occurred_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        data = { }, )
                    ],
                next_cursor = '',
                has_more = True,
        )
        """

    def testChangePageOut(self):
        """Test ChangePageOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
