/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: <PINNED>
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GrantCreateIn,
  GrantListOut,
  GrantOut,
  GrantUpdateIn,
  V0ErrorEnvelope,
  ValidationErrorResponse,
} from '../models/index';
import {
    GrantCreateInFromJSON,
    GrantCreateInToJSON,
    GrantListOutFromJSON,
    GrantListOutToJSON,
    GrantOutFromJSON,
    GrantOutToJSON,
    GrantUpdateInFromJSON,
    GrantUpdateInToJSON,
    V0ErrorEnvelopeFromJSON,
    V0ErrorEnvelopeToJSON,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/index';

export interface GrantsCreateRequest {
    driveId: string;
    idempotencyKey: string | null;
    grantCreateIn: GrantCreateIn;
    authorization?: string | null;
}

export interface GrantsListRequest {
    driveId: string;
    lifecycle?: string;
    limit?: number | null;
    cursor?: string | null;
    resourceType?: string | null;
    resourceId?: string | null;
    principalType?: string | null;
    authorization?: string | null;
}

export interface GrantsReadRequest {
    driveId: string;
    grantId: string;
    ifNoneMatch?: string | null;
    authorization?: string | null;
}

export interface GrantsRevokeRequest {
    driveId: string;
    grantId: string;
    idempotencyKey: string | null;
    ifMatch: string | null;
    authorization?: string | null;
}

export interface GrantsUpdateRequest {
    driveId: string;
    grantId: string;
    idempotencyKey: string | null;
    ifMatch: string | null;
    grantUpdateIn: GrantUpdateIn;
    authorization?: string | null;
}

/**
 *
 */
export class GrantsApi extends runtime.BaseAPI {

    /**
     * Grant one principal a role on a drive, folder, or artifact.
     * Create Grant
     */
    async grantsCreateRaw(requestParameters: GrantsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GrantOut>> {
        if (requestParameters['driveId'] == null) {
            throw new runtime.RequiredError(
                'driveId',
                'Required parameter "driveId" was null or undefined when calling grantsCreate().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling grantsCreate().'
            );
        }

        if (requestParameters['grantCreateIn'] == null) {
            throw new runtime.RequiredError(
                'grantCreateIn',
                'Required parameter "grantCreateIn" was null or undefined when calling grantsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v0/drives/{drive_id}/grants`;
        urlPath = urlPath.replace(`{${"drive_id"}}`, encodeURIComponent(String(requestParameters['driveId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GrantCreateInToJSON(requestParameters['grantCreateIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GrantOutFromJSON(jsonValue));
    }

    /**
     * Grant one principal a role on a drive, folder, or artifact.
     * Create Grant
     */
    async grantsCreate(requestParameters: GrantsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GrantOut> {
        const response = await this.grantsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List explicit grants in the drive, keyset paginated.  **What you see depends on your role (contract change).** A caller holding ``manager`` on the drive lists EVERY grant in it. Any other caller lists only the grants that name them — their own agent/user rows, ``workspace`` grants covering them, and ``public`` grants (which already expose the resource to them anyway). Previously any drive ``viewer`` could page out every principal id, role and expiry in the drive; that was an access-graph disclosure, not a feature.  The operation is refused (404) only for a caller holding no live grant anywhere in the drive — never for lack of ``manager``, because seeing your own access is not a privilege. That admits folder-scoped principals, who previously 404\'d here despite having access to show. A folder ``manager`` still sees only their own rows, not the roster of the subtree they administer; scoping the listing by per-resource administration authority is a follow-up this change does not claim.  ``resource_id`` filters to one resource\'s grants and REQUIRES ``resource_type`` alongside it — a bare resource id is ambiguous across the three resource kinds, and guessing the kind from the id prefix would make the filter\'s meaning depend on an id format the contract does not promise to keep. ``resource_type`` on its own remains a valid (and pre-existing) filter.
     * List Grants
     */
    async grantsListRaw(requestParameters: GrantsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GrantListOut>> {
        if (requestParameters['driveId'] == null) {
            throw new runtime.RequiredError(
                'driveId',
                'Required parameter "driveId" was null or undefined when calling grantsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lifecycle'] != null) {
            queryParameters['lifecycle'] = requestParameters['lifecycle'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['resourceType'] != null) {
            queryParameters['resource_type'] = requestParameters['resourceType'];
        }

        if (requestParameters['resourceId'] != null) {
            queryParameters['resource_id'] = requestParameters['resourceId'];
        }

        if (requestParameters['principalType'] != null) {
            queryParameters['principal_type'] = requestParameters['principalType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v0/drives/{drive_id}/grants`;
        urlPath = urlPath.replace(`{${"drive_id"}}`, encodeURIComponent(String(requestParameters['driveId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GrantListOutFromJSON(jsonValue));
    }

    /**
     * List explicit grants in the drive, keyset paginated.  **What you see depends on your role (contract change).** A caller holding ``manager`` on the drive lists EVERY grant in it. Any other caller lists only the grants that name them — their own agent/user rows, ``workspace`` grants covering them, and ``public`` grants (which already expose the resource to them anyway). Previously any drive ``viewer`` could page out every principal id, role and expiry in the drive; that was an access-graph disclosure, not a feature.  The operation is refused (404) only for a caller holding no live grant anywhere in the drive — never for lack of ``manager``, because seeing your own access is not a privilege. That admits folder-scoped principals, who previously 404\'d here despite having access to show. A folder ``manager`` still sees only their own rows, not the roster of the subtree they administer; scoping the listing by per-resource administration authority is a follow-up this change does not claim.  ``resource_id`` filters to one resource\'s grants and REQUIRES ``resource_type`` alongside it — a bare resource id is ambiguous across the three resource kinds, and guessing the kind from the id prefix would make the filter\'s meaning depend on an id format the contract does not promise to keep. ``resource_type`` on its own remains a valid (and pre-existing) filter.
     * List Grants
     */
    async grantsList(requestParameters: GrantsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GrantListOut> {
        const response = await this.grantsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read one grant in the drive.
     * Read Grant
     */
    async grantsReadRaw(requestParameters: GrantsReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GrantOut>> {
        if (requestParameters['driveId'] == null) {
            throw new runtime.RequiredError(
                'driveId',
                'Required parameter "driveId" was null or undefined when calling grantsRead().'
            );
        }

        if (requestParameters['grantId'] == null) {
            throw new runtime.RequiredError(
                'grantId',
                'Required parameter "grantId" was null or undefined when calling grantsRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v0/drives/{drive_id}/grants/{grant_id}`;
        urlPath = urlPath.replace(`{${"drive_id"}}`, encodeURIComponent(String(requestParameters['driveId'])));
        urlPath = urlPath.replace(`{${"grant_id"}}`, encodeURIComponent(String(requestParameters['grantId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GrantOutFromJSON(jsonValue));
    }

    /**
     * Read one grant in the drive.
     * Read Grant
     */
    async grantsRead(requestParameters: GrantsReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GrantOut> {
        const response = await this.grantsReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke a grant (soft, sets revoked_at) under If-Match.
     * Revoke Grant
     */
    async grantsRevokeRaw(requestParameters: GrantsRevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GrantOut>> {
        if (requestParameters['driveId'] == null) {
            throw new runtime.RequiredError(
                'driveId',
                'Required parameter "driveId" was null or undefined when calling grantsRevoke().'
            );
        }

        if (requestParameters['grantId'] == null) {
            throw new runtime.RequiredError(
                'grantId',
                'Required parameter "grantId" was null or undefined when calling grantsRevoke().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling grantsRevoke().'
            );
        }

        if (requestParameters['ifMatch'] == null) {
            throw new runtime.RequiredError(
                'ifMatch',
                'Required parameter "ifMatch" was null or undefined when calling grantsRevoke().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v0/drives/{drive_id}/grants/{grant_id}`;
        urlPath = urlPath.replace(`{${"drive_id"}}`, encodeURIComponent(String(requestParameters['driveId'])));
        urlPath = urlPath.replace(`{${"grant_id"}}`, encodeURIComponent(String(requestParameters['grantId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GrantOutFromJSON(jsonValue));
    }

    /**
     * Revoke a grant (soft, sets revoked_at) under If-Match.
     * Revoke Grant
     */
    async grantsRevoke(requestParameters: GrantsRevokeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GrantOut> {
        const response = await this.grantsRevokeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change a grant\'s role or expiry under If-Match.
     * Update Grant
     */
    async grantsUpdateRaw(requestParameters: GrantsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GrantOut>> {
        if (requestParameters['driveId'] == null) {
            throw new runtime.RequiredError(
                'driveId',
                'Required parameter "driveId" was null or undefined when calling grantsUpdate().'
            );
        }

        if (requestParameters['grantId'] == null) {
            throw new runtime.RequiredError(
                'grantId',
                'Required parameter "grantId" was null or undefined when calling grantsUpdate().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling grantsUpdate().'
            );
        }

        if (requestParameters['ifMatch'] == null) {
            throw new runtime.RequiredError(
                'ifMatch',
                'Required parameter "ifMatch" was null or undefined when calling grantsUpdate().'
            );
        }

        if (requestParameters['grantUpdateIn'] == null) {
            throw new runtime.RequiredError(
                'grantUpdateIn',
                'Required parameter "grantUpdateIn" was null or undefined when calling grantsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (requestParameters['ifMatch'] != null) {
            headerParameters['If-Match'] = String(requestParameters['ifMatch']);
        }

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v0/drives/{drive_id}/grants/{grant_id}`;
        urlPath = urlPath.replace(`{${"drive_id"}}`, encodeURIComponent(String(requestParameters['driveId'])));
        urlPath = urlPath.replace(`{${"grant_id"}}`, encodeURIComponent(String(requestParameters['grantId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: GrantUpdateInToJSON(requestParameters['grantUpdateIn']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GrantOutFromJSON(jsonValue));
    }

    /**
     * Change a grant\'s role or expiry under If-Match.
     * Update Grant
     */
    async grantsUpdate(requestParameters: GrantsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GrantOut> {
        const response = await this.grantsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
