/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: <PINNED>
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type InvitationList,
    InvitationListFromJSON,
    InvitationListToJSON,
} from '../models/InvitationList';
import {
    type InviteCreateOut,
    InviteCreateOutFromJSON,
    InviteCreateOutToJSON,
} from '../models/InviteCreateOut';
import {
    type MemberInviteIn,
    MemberInviteInFromJSON,
    MemberInviteInToJSON,
} from '../models/MemberInviteIn';
import {
    type MemberList,
    MemberListFromJSON,
    MemberListToJSON,
} from '../models/MemberList';
import {
    type MemberOut,
    MemberOutFromJSON,
    MemberOutToJSON,
} from '../models/MemberOut';
import {
    type MemberRemoveOut,
    MemberRemoveOutFromJSON,
    MemberRemoveOutToJSON,
} from '../models/MemberRemoveOut';
import {
    type MemberRoleIn,
    MemberRoleInFromJSON,
    MemberRoleInToJSON,
} from '../models/MemberRoleIn';
import {
    type RevokeOut,
    RevokeOutFromJSON,
    RevokeOutToJSON,
} from '../models/RevokeOut';
import {
    type ValidationErrorResponse,
    ValidationErrorResponseFromJSON,
    ValidationErrorResponseToJSON,
} from '../models/ValidationErrorResponse';

export interface InviteMemberV0MembersInvitePostRequest {
    memberInviteIn: MemberInviteIn;
}

export interface ListInvitationsV0InvitationsGetRequest {
    cursor?: string | null;
    limit?: number | null;
}

export interface ListMembersV0MembersGetRequest {
    cursor?: string | null;
    limit?: number | null;
}

export interface RemoveMemberV0MembersTargetUserIdDeleteRequest {
    targetUserId: string;
    confirm?: string | null;
}

export interface RevokeInvitationV0InvitationsInvitationIdDeleteRequest {
    invitationId: string;
}

export interface SetMemberRoleV0MembersTargetUserIdPatchRequest {
    targetUserId: string;
    memberRoleIn: MemberRoleIn;
}

/**
 *
 */
export class MembersApi extends runtime.BaseAPI {

    /**
     * Creates request options for inviteMemberV0MembersInvitePost without sending the request
     */
    async inviteMemberV0MembersInvitePostRequestOpts(requestParameters: InviteMemberV0MembersInvitePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['memberInviteIn'] == null) {
            throw new runtime.RequiredError(
                'memberInviteIn',
                'Required parameter "memberInviteIn" was null or undefined when calling inviteMemberV0MembersInvitePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v0/members/invite`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MemberInviteInToJSON(requestParameters['memberInviteIn']),
        };
    }

    /**
     * Create a pending invitation in the caller\'s active workspace and enqueue the invite email. **Admin only**, `full` scope. Inviting an existing member is a no-op success (`already_member: true`). A duplicate pending invite for the same email returns 409 `INVITE_PENDING` (resend it from the members page). The raw invite token is delivered only by email — never in this response.
     * Invite a person to your workspace by email
     */
    async inviteMemberV0MembersInvitePostRaw(requestParameters: InviteMemberV0MembersInvitePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InviteCreateOut>> {
        const requestOptions = await this.inviteMemberV0MembersInvitePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InviteCreateOutFromJSON(jsonValue));
    }

    /**
     * Create a pending invitation in the caller\'s active workspace and enqueue the invite email. **Admin only**, `full` scope. Inviting an existing member is a no-op success (`already_member: true`). A duplicate pending invite for the same email returns 409 `INVITE_PENDING` (resend it from the members page). The raw invite token is delivered only by email — never in this response.
     * Invite a person to your workspace by email
     */
    async inviteMemberV0MembersInvitePost(requestParameters: InviteMemberV0MembersInvitePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InviteCreateOut> {
        const response = await this.inviteMemberV0MembersInvitePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listInvitationsV0InvitationsGet without sending the request
     */
    async listInvitationsV0InvitationsGetRequestOpts(requestParameters: ListInvitationsV0InvitationsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v0/invitations`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the pending invitations for the caller\'s active workspace. **Admin only.** Metadata only — the raw invite token is never surfaced.  Newest first (`created_at` descending, tie-broken by `id`). Paginated: `limit` is clamped to [1, 100] (default 50, never a 422); pass the response\'s `next_cursor` back as `cursor` for the next page (`null` when the listing is complete).
     * List pending invitations
     */
    async listInvitationsV0InvitationsGetRaw(requestParameters: ListInvitationsV0InvitationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvitationList>> {
        const requestOptions = await this.listInvitationsV0InvitationsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvitationListFromJSON(jsonValue));
    }

    /**
     * List the pending invitations for the caller\'s active workspace. **Admin only.** Metadata only — the raw invite token is never surfaced.  Newest first (`created_at` descending, tie-broken by `id`). Paginated: `limit` is clamped to [1, 100] (default 50, never a 422); pass the response\'s `next_cursor` back as `cursor` for the next page (`null` when the listing is complete).
     * List pending invitations
     */
    async listInvitationsV0InvitationsGet(requestParameters: ListInvitationsV0InvitationsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvitationList> {
        const response = await this.listInvitationsV0InvitationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMembersV0MembersGet without sending the request
     */
    async listMembersV0MembersGetRequestOpts(requestParameters: ListMembersV0MembersGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v0/members`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List live members (email, role, joined-at) of the caller\'s active workspace. Any **member** may list; a `read`-scope token is sufficient.  Ordered by join time (`created_at`, tie-broken by `user_id`) — **no role grouping is promised**; a dashboard that wants admins-first sorts client-side. Paginated: `limit` is clamped to [1, 100] (default 50, never a 422); pass the response\'s `next_cursor` back as `cursor` for the next page (`null` when the listing is complete).
     * List the members of your active workspace
     */
    async listMembersV0MembersGetRaw(requestParameters: ListMembersV0MembersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemberList>> {
        const requestOptions = await this.listMembersV0MembersGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemberListFromJSON(jsonValue));
    }

    /**
     * List live members (email, role, joined-at) of the caller\'s active workspace. Any **member** may list; a `read`-scope token is sufficient.  Ordered by join time (`created_at`, tie-broken by `user_id`) — **no role grouping is promised**; a dashboard that wants admins-first sorts client-side. Paginated: `limit` is clamped to [1, 100] (default 50, never a 422); pass the response\'s `next_cursor` back as `cursor` for the next page (`null` when the listing is complete).
     * List the members of your active workspace
     */
    async listMembersV0MembersGet(requestParameters: ListMembersV0MembersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemberList> {
        const response = await this.listMembersV0MembersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeMemberV0MembersTargetUserIdDelete without sending the request
     */
    async removeMemberV0MembersTargetUserIdDeleteRequestOpts(requestParameters: RemoveMemberV0MembersTargetUserIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['targetUserId'] == null) {
            throw new runtime.RequiredError(
                'targetUserId',
                'Required parameter "targetUserId" was null or undefined when calling removeMemberV0MembersTargetUserIdDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['confirm'] != null) {
            queryParameters['confirm'] = requestParameters['confirm'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v0/members/{target_user_id}`;
        urlPath = urlPath.replace('{target_user_id}', encodeURIComponent(String(requestParameters['targetUserId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove a member from the caller\'s active workspace, soft-deleting every drive that member owns there (workspaces-design §4.4 — no ownership transfer in v0; their `ad_live_` keys then stop working). **Admin** may remove anyone; **any member** may remove themselves (self-leave). `full` scope. Removing the **last/sole admin** is rejected with 409 `LAST_ADMIN` (promote someone first, or delete the workspace).  **Explicit confirmation required:** pass `?confirm=DELETE` or the request is rejected with 400 `CONFIRM_REQUIRED` — removal cascades a soft-delete of every drive the member owns, so it carries tenant-level blast radius (uniform with `DELETE /v0/drives/{id}`).  Deliberately takes NO `If-Match`: membership rows carry no generation/metageneration axis to pin (there is no ETag to echo), so `?confirm=DELETE` is the sole mutation guard here.
     * Remove a member (or leave)
     */
    async removeMemberV0MembersTargetUserIdDeleteRaw(requestParameters: RemoveMemberV0MembersTargetUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemberRemoveOut>> {
        const requestOptions = await this.removeMemberV0MembersTargetUserIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemberRemoveOutFromJSON(jsonValue));
    }

    /**
     * Remove a member from the caller\'s active workspace, soft-deleting every drive that member owns there (workspaces-design §4.4 — no ownership transfer in v0; their `ad_live_` keys then stop working). **Admin** may remove anyone; **any member** may remove themselves (self-leave). `full` scope. Removing the **last/sole admin** is rejected with 409 `LAST_ADMIN` (promote someone first, or delete the workspace).  **Explicit confirmation required:** pass `?confirm=DELETE` or the request is rejected with 400 `CONFIRM_REQUIRED` — removal cascades a soft-delete of every drive the member owns, so it carries tenant-level blast radius (uniform with `DELETE /v0/drives/{id}`).  Deliberately takes NO `If-Match`: membership rows carry no generation/metageneration axis to pin (there is no ETag to echo), so `?confirm=DELETE` is the sole mutation guard here.
     * Remove a member (or leave)
     */
    async removeMemberV0MembersTargetUserIdDelete(requestParameters: RemoveMemberV0MembersTargetUserIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemberRemoveOut> {
        const response = await this.removeMemberV0MembersTargetUserIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for revokeInvitationV0InvitationsInvitationIdDelete without sending the request
     */
    async revokeInvitationV0InvitationsInvitationIdDeleteRequestOpts(requestParameters: RevokeInvitationV0InvitationsInvitationIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['invitationId'] == null) {
            throw new runtime.RequiredError(
                'invitationId',
                'Required parameter "invitationId" was null or undefined when calling revokeInvitationV0InvitationsInvitationIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v0/invitations/{invitation_id}`;
        urlPath = urlPath.replace('{invitation_id}', encodeURIComponent(String(requestParameters['invitationId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Revoke a pending invitation in the caller\'s active workspace. **Admin only**, `full` scope. Org-scoped + idempotent: `revoked` is a COUNT — 1 when a live invite was revoked, 0 when it was already gone (a forged id, an invite from another workspace, or an already-consumed invite all return `revoked: 0`, no-leak).
     * Revoke a pending invitation
     */
    async revokeInvitationV0InvitationsInvitationIdDeleteRaw(requestParameters: RevokeInvitationV0InvitationsInvitationIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RevokeOut>> {
        const requestOptions = await this.revokeInvitationV0InvitationsInvitationIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RevokeOutFromJSON(jsonValue));
    }

    /**
     * Revoke a pending invitation in the caller\'s active workspace. **Admin only**, `full` scope. Org-scoped + idempotent: `revoked` is a COUNT — 1 when a live invite was revoked, 0 when it was already gone (a forged id, an invite from another workspace, or an already-consumed invite all return `revoked: 0`, no-leak).
     * Revoke a pending invitation
     */
    async revokeInvitationV0InvitationsInvitationIdDelete(requestParameters: RevokeInvitationV0InvitationsInvitationIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RevokeOut> {
        const response = await this.revokeInvitationV0InvitationsInvitationIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setMemberRoleV0MembersTargetUserIdPatch without sending the request
     */
    async setMemberRoleV0MembersTargetUserIdPatchRequestOpts(requestParameters: SetMemberRoleV0MembersTargetUserIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['targetUserId'] == null) {
            throw new runtime.RequiredError(
                'targetUserId',
                'Required parameter "targetUserId" was null or undefined when calling setMemberRoleV0MembersTargetUserIdPatch().'
            );
        }

        if (requestParameters['memberRoleIn'] == null) {
            throw new runtime.RequiredError(
                'memberRoleIn',
                'Required parameter "memberRoleIn" was null or undefined when calling setMemberRoleV0MembersTargetUserIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v0/members/{target_user_id}`;
        urlPath = urlPath.replace('{target_user_id}', encodeURIComponent(String(requestParameters['targetUserId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MemberRoleInToJSON(requestParameters['memberRoleIn']),
        };
    }

    /**
     * Promote/demote a member in the caller\'s active workspace. **Admin only**, `full` scope. Demoting the workspace\'s **last admin** is rejected with 409 `LAST_ADMIN` (promote someone first).
     * Change a member\'s role
     */
    async setMemberRoleV0MembersTargetUserIdPatchRaw(requestParameters: SetMemberRoleV0MembersTargetUserIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemberOut>> {
        const requestOptions = await this.setMemberRoleV0MembersTargetUserIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemberOutFromJSON(jsonValue));
    }

    /**
     * Promote/demote a member in the caller\'s active workspace. **Admin only**, `full` scope. Demoting the workspace\'s **last admin** is rejected with 409 `LAST_ADMIN` (promote someone first).
     * Change a member\'s role
     */
    async setMemberRoleV0MembersTargetUserIdPatch(requestParameters: SetMemberRoleV0MembersTargetUserIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemberOut> {
        const response = await this.setMemberRoleV0MembersTargetUserIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
