# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: <PINNED>
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from agentdrive_sdk.models.claim_metadata import ClaimMetadata
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AnonymousIdentityResponse(BaseModel):
    """
    `POST /agent/identity` response on the anonymous path.  The agent stores `identity_assertion` as its long-lived credential and uses `claim_token` to initiate the claim ceremony when the human is ready.
    """ # noqa: E501
    agent_identity_id: StrictStr
    claim_metadata: ClaimMetadata
    claim_token: StrictStr = Field(description="Opaque server-issued secret. Present at POST /agent/identity/claim and at POST /oauth2/token (grant_type=claim).")
    drive_id: StrictStr
    expires_at: datetime
    identity_assertion: StrictStr = Field(description="JWT signed by AgentDrive, scope=pre_claim. 30-day TTL.")
    __properties: ClassVar[List[str]] = ["agent_identity_id", "claim_metadata", "claim_token", "drive_id", "expires_at", "identity_assertion"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnonymousIdentityResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of claim_metadata
        if self.claim_metadata:
            _dict['claim_metadata'] = self.claim_metadata.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnonymousIdentityResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agent_identity_id": obj.get("agent_identity_id"),
            "claim_metadata": ClaimMetadata.from_dict(obj["claim_metadata"]) if obj.get("claim_metadata") is not None else None,
            "claim_token": obj.get("claim_token"),
            "drive_id": obj.get("drive_id"),
            "expires_at": obj.get("expires_at"),
            "identity_assertion": obj.get("identity_assertion")
        })
        return _obj
