/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: <PINNED>
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// AgentAuthAPIService AgentAuthAPI service
type AgentAuthAPIService service

type ApiExtensionExchangeV0AuthExtensionExchangePostRequest struct {
	ctx context.Context
	ApiService *AgentAuthAPIService
	extensionExchangeRequest *ExtensionExchangeRequest
}

func (r ApiExtensionExchangeV0AuthExtensionExchangePostRequest) ExtensionExchangeRequest(extensionExchangeRequest ExtensionExchangeRequest) ApiExtensionExchangeV0AuthExtensionExchangePostRequest {
	r.extensionExchangeRequest = &extensionExchangeRequest
	return r
}

func (r ApiExtensionExchangeV0AuthExtensionExchangePostRequest) Execute() (*ExtensionExchangeResponse, *http.Response, error) {
	return r.ApiService.ExtensionExchangeV0AuthExtensionExchangePostExecute(r)
}

/*
ExtensionExchangeV0AuthExtensionExchangePost Redeem an extension OAuth ticket for a JWT pair

Single-use opaque ticket → JWT pair. Called once by an extension's auth-complete.html after the OAuth handoff lands. Returns a 15-minute `access_token` (scope=extension) and a 90-day `identity_assertion` the extension stores and refreshes via POST /oauth2/token.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiExtensionExchangeV0AuthExtensionExchangePostRequest
*/
func (a *AgentAuthAPIService) ExtensionExchangeV0AuthExtensionExchangePost(ctx context.Context) ApiExtensionExchangeV0AuthExtensionExchangePostRequest {
	return ApiExtensionExchangeV0AuthExtensionExchangePostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ExtensionExchangeResponse
func (a *AgentAuthAPIService) ExtensionExchangeV0AuthExtensionExchangePostExecute(r ApiExtensionExchangeV0AuthExtensionExchangePostRequest) (*ExtensionExchangeResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ExtensionExchangeResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentAuthAPIService.ExtensionExchangeV0AuthExtensionExchangePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v0/auth/extension/exchange"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.extensionExchangeRequest == nil {
		return localVarReturnValue, nil, reportError("extensionExchangeRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.extensionExchangeRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ValidationErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiInitiateClaimAgentIdentityClaimPostRequest struct {
	ctx context.Context
	ApiService *AgentAuthAPIService
	claimInitRequest *ClaimInitRequest
}

func (r ApiInitiateClaimAgentIdentityClaimPostRequest) ClaimInitRequest(claimInitRequest ClaimInitRequest) ApiInitiateClaimAgentIdentityClaimPostRequest {
	r.claimInitRequest = &claimInitRequest
	return r
}

func (r ApiInitiateClaimAgentIdentityClaimPostRequest) Execute() (*ClaimInitResponse, *http.Response, error) {
	return r.ApiService.InitiateClaimAgentIdentityClaimPostExecute(r)
}

/*
InitiateClaimAgentIdentityClaimPost Initiate the human-claim ceremony for an agent identity

Returns a `user_code` and `verification_uri` (RFC 8628 device-code idiom). The agent surfaces these to the human, who visits the URI, signs in, and approves the claim. The agent then polls POST /oauth2/token (grant_type=claim) with the same `claim_token` to learn when the claim completes.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiInitiateClaimAgentIdentityClaimPostRequest
*/
func (a *AgentAuthAPIService) InitiateClaimAgentIdentityClaimPost(ctx context.Context) ApiInitiateClaimAgentIdentityClaimPostRequest {
	return ApiInitiateClaimAgentIdentityClaimPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ClaimInitResponse
func (a *AgentAuthAPIService) InitiateClaimAgentIdentityClaimPostExecute(r ApiInitiateClaimAgentIdentityClaimPostRequest) (*ClaimInitResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ClaimInitResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentAuthAPIService.InitiateClaimAgentIdentityClaimPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/agent/identity/claim"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.claimInitRequest == nil {
		return localVarReturnValue, nil, reportError("claimInitRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.claimInitRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ValidationErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiJwksWellKnownJwksJsonGetRequest struct {
	ctx context.Context
	ApiService *AgentAuthAPIService
}

func (r ApiJwksWellKnownJwksJsonGetRequest) Execute() (*JwksOut, *http.Response, error) {
	return r.ApiService.JwksWellKnownJwksJsonGetExecute(r)
}

/*
JwksWellKnownJwksJsonGet JSON Web Key Set — public keys for verifying AgentDrive JWTs

Public half of the RSA signing key for identity_assertion + access_token JWTs issued by AgentDrive. RFC 7517 shape. Cache-friendly; key rotation publishes both kids during the overlap window.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiJwksWellKnownJwksJsonGetRequest
*/
func (a *AgentAuthAPIService) JwksWellKnownJwksJsonGet(ctx context.Context) ApiJwksWellKnownJwksJsonGetRequest {
	return ApiJwksWellKnownJwksJsonGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return JwksOut
func (a *AgentAuthAPIService) JwksWellKnownJwksJsonGetExecute(r ApiJwksWellKnownJwksJsonGetRequest) (*JwksOut, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *JwksOut
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentAuthAPIService.JwksWellKnownJwksJsonGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/.well-known/jwks.json"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiOauth2TokenOauth2TokenPostRequest struct {
	ctx context.Context
	ApiService *AgentAuthAPIService
	grantType *string
	assertion *string
	claimToken *string
}

func (r ApiOauth2TokenOauth2TokenPostRequest) GrantType(grantType string) ApiOauth2TokenOauth2TokenPostRequest {
	r.grantType = &grantType
	return r
}

func (r ApiOauth2TokenOauth2TokenPostRequest) Assertion(assertion string) ApiOauth2TokenOauth2TokenPostRequest {
	r.assertion = &assertion
	return r
}

func (r ApiOauth2TokenOauth2TokenPostRequest) ClaimToken(claimToken string) ApiOauth2TokenOauth2TokenPostRequest {
	r.claimToken = &claimToken
	return r
}

func (r ApiOauth2TokenOauth2TokenPostRequest) Execute() (*TokenResponse, *http.Response, error) {
	return r.ApiService.Oauth2TokenOauth2TokenPostExecute(r)
}

/*
Oauth2TokenOauth2TokenPost Exchange a credential for an access_token

Two grant types:

**`urn:ietf:params:oauth:grant-type:jwt-bearer`** (RFC 7523) — body `assertion=<identity_assertion JWT>`. Returns a fresh 15-minute access_token with the same scope as the assertion.

**`claim`** (custom) — body `claim_token=<from POST /agent/identity>`. Polling endpoint for the claim ceremony. Returns one of: `authorization_pending` (400), `expired_token` (400), `access_denied` (400), or access_token + new identity_assertion + scope=full (200).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiOauth2TokenOauth2TokenPostRequest
*/
func (a *AgentAuthAPIService) Oauth2TokenOauth2TokenPost(ctx context.Context) ApiOauth2TokenOauth2TokenPostRequest {
	return ApiOauth2TokenOauth2TokenPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return TokenResponse
func (a *AgentAuthAPIService) Oauth2TokenOauth2TokenPostExecute(r ApiOauth2TokenOauth2TokenPostRequest) (*TokenResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TokenResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentAuthAPIService.Oauth2TokenOauth2TokenPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/oauth2/token"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.grantType == nil {
		return localVarReturnValue, nil, reportError("grantType is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/x-www-form-urlencoded"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.assertion != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "assertion", r.assertion, "", "")
	}
	if r.claimToken != nil {
		parameterAddToHeaderOrQuery(localVarFormParams, "claim_token", r.claimToken, "", "")
	}
	parameterAddToHeaderOrQuery(localVarFormParams, "grant_type", r.grantType, "", "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ValidationErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiOauthAuthorizationServerWellKnownOauthAuthorizationServerGetRequest struct {
	ctx context.Context
	ApiService *AgentAuthAPIService
}

func (r ApiOauthAuthorizationServerWellKnownOauthAuthorizationServerGetRequest) Execute() (*AuthorizationServerMetadataOut, *http.Response, error) {
	return r.ApiService.OauthAuthorizationServerWellKnownOauthAuthorizationServerGetExecute(r)
}

/*
OauthAuthorizationServerWellKnownOauthAuthorizationServerGet Authorization-server metadata (RFC 8414 + auth.md agent_auth block)

Discovery document for the auth.md protocol. Carries the standard RFC 8414 fields plus an `agent_auth` block per the auth.md spec — the latter is what an agent runtime keys off to find the identity + claim endpoints.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiOauthAuthorizationServerWellKnownOauthAuthorizationServerGetRequest
*/
func (a *AgentAuthAPIService) OauthAuthorizationServerWellKnownOauthAuthorizationServerGet(ctx context.Context) ApiOauthAuthorizationServerWellKnownOauthAuthorizationServerGetRequest {
	return ApiOauthAuthorizationServerWellKnownOauthAuthorizationServerGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return AuthorizationServerMetadataOut
func (a *AgentAuthAPIService) OauthAuthorizationServerWellKnownOauthAuthorizationServerGetExecute(r ApiOauthAuthorizationServerWellKnownOauthAuthorizationServerGetRequest) (*AuthorizationServerMetadataOut, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AuthorizationServerMetadataOut
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentAuthAPIService.OauthAuthorizationServerWellKnownOauthAuthorizationServerGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/.well-known/oauth-authorization-server"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpGetRequest struct {
	ctx context.Context
	ApiService *AgentAuthAPIService
}

func (r ApiOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpGetRequest) Execute() (*ProtectedResourceMetadataOut, *http.Response, error) {
	return r.ApiService.OauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpGetExecute(r)
}

/*
OauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpGet Protected-resource metadata for the MCP endpoint (RFC 9728 §3.1)

Path-inserted variant of the protected-resource document. MCP clients derive this URL from the resource URL `{origin}/mcp` (RFC 9728 §3.1: insert the well-known segment between host and path) after reading the WWW-Authenticate challenge on a 401 — it is the first hop of the client-side OAuth flow.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpGetRequest
*/
func (a *AgentAuthAPIService) OauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpGet(ctx context.Context) ApiOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpGetRequest {
	return ApiOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ProtectedResourceMetadataOut
func (a *AgentAuthAPIService) OauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpGetExecute(r ApiOauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpGetRequest) (*ProtectedResourceMetadataOut, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ProtectedResourceMetadataOut
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentAuthAPIService.OauthProtectedResourceMcpWellKnownOauthProtectedResourceMcpGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/.well-known/oauth-protected-resource/mcp"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiOauthProtectedResourceWellKnownOauthProtectedResourceGetRequest struct {
	ctx context.Context
	ApiService *AgentAuthAPIService
}

func (r ApiOauthProtectedResourceWellKnownOauthProtectedResourceGetRequest) Execute() (*ProtectedResourceMetadataOut, *http.Response, error) {
	return r.ApiService.OauthProtectedResourceWellKnownOauthProtectedResourceGetExecute(r)
}

/*
OauthProtectedResourceWellKnownOauthProtectedResourceGet Protected-resource metadata (auth.md / RFC 9728-like discovery)

Names this server as a protected resource and points clients at the authorization server they should obtain tokens from. In this design the resource server and authorization server are the same host.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiOauthProtectedResourceWellKnownOauthProtectedResourceGetRequest
*/
func (a *AgentAuthAPIService) OauthProtectedResourceWellKnownOauthProtectedResourceGet(ctx context.Context) ApiOauthProtectedResourceWellKnownOauthProtectedResourceGetRequest {
	return ApiOauthProtectedResourceWellKnownOauthProtectedResourceGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ProtectedResourceMetadataOut
func (a *AgentAuthAPIService) OauthProtectedResourceWellKnownOauthProtectedResourceGetExecute(r ApiOauthProtectedResourceWellKnownOauthProtectedResourceGetRequest) (*ProtectedResourceMetadataOut, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ProtectedResourceMetadataOut
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentAuthAPIService.OauthProtectedResourceWellKnownOauthProtectedResourceGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/.well-known/oauth-protected-resource"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRegisterAgentIdentityAgentIdentityPostRequest struct {
	ctx context.Context
	ApiService *AgentAuthAPIService
	requestBody *map[string]*interface{}
}

func (r ApiRegisterAgentIdentityAgentIdentityPostRequest) RequestBody(requestBody map[string]*interface{}) ApiRegisterAgentIdentityAgentIdentityPostRequest {
	r.requestBody = &requestBody
	return r
}

func (r ApiRegisterAgentIdentityAgentIdentityPostRequest) Execute() (*AnonymousIdentityResponse, *http.Response, error) {
	return r.ApiService.RegisterAgentIdentityAgentIdentityPostExecute(r)
}

/*
RegisterAgentIdentityAgentIdentityPost Register an agent identity (anonymous or ID-JAG)

Two registration modes:

**`type=anonymous`** — Provisions a brand-new agent identity bound to a fresh shadow-org drive. No human involved; returned `identity_assertion` carries `scope=pre_claim`. A human completes the claim ceremony later via /claim.

**`type=identity_assertion`** — Agent provider (e.g. WorkOS) has already minted an ID-JAG asserting a user identity binding. We verify it against the provider's JWKS and provision a **claimed** identity immediately: scope=full, drive bound to the user, no claim ceremony needed.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiRegisterAgentIdentityAgentIdentityPostRequest
*/
func (a *AgentAuthAPIService) RegisterAgentIdentityAgentIdentityPost(ctx context.Context) ApiRegisterAgentIdentityAgentIdentityPostRequest {
	return ApiRegisterAgentIdentityAgentIdentityPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return AnonymousIdentityResponse
func (a *AgentAuthAPIService) RegisterAgentIdentityAgentIdentityPostExecute(r ApiRegisterAgentIdentityAgentIdentityPostRequest) (*AnonymousIdentityResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AnonymousIdentityResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AgentAuthAPIService.RegisterAgentIdentityAgentIdentityPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/agent/identity"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestBody == nil {
		return localVarReturnValue, nil, reportError("requestBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v RegisterAgentIdentityAgentIdentityPost422Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
