/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: <PINNED>
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DriveReadOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DriveReadOut{}

// DriveReadOut Drive singleton shape returned by both data-plane read routes.
type DriveReadOut struct {
	CreatedAt time.Time `json:"created_at"`
	Email NullableString `json:"email,omitempty"`
	Etag string `json:"etag"`
	Id string `json:"id"`
	Metageneration int32 `json:"metageneration"`
	OrganizationId string `json:"organization_id"`
	StorageBytes int32 `json:"storage_bytes"`
	StorageLimit int32 `json:"storage_limit"`
}

type _DriveReadOut DriveReadOut

// NewDriveReadOut instantiates a new DriveReadOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDriveReadOut(createdAt time.Time, etag string, id string, metageneration int32, organizationId string, storageBytes int32, storageLimit int32) *DriveReadOut {
	this := DriveReadOut{}
	this.CreatedAt = createdAt
	this.Etag = etag
	this.Id = id
	this.Metageneration = metageneration
	this.OrganizationId = organizationId
	this.StorageBytes = storageBytes
	this.StorageLimit = storageLimit
	return &this
}

// NewDriveReadOutWithDefaults instantiates a new DriveReadOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDriveReadOutWithDefaults() *DriveReadOut {
	this := DriveReadOut{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *DriveReadOut) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DriveReadOut) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DriveReadOut) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DriveReadOut) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DriveReadOut) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *DriveReadOut) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *DriveReadOut) SetEmail(v string) {
	o.Email.Set(&v)
}
// SetEmailNil sets the value for Email to be an explicit nil
func (o *DriveReadOut) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *DriveReadOut) UnsetEmail() {
	o.Email.Unset()
}

// GetEtag returns the Etag field value
func (o *DriveReadOut) GetEtag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Etag
}

// GetEtagOk returns a tuple with the Etag field value
// and a boolean to check if the value has been set.
func (o *DriveReadOut) GetEtagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Etag, true
}

// SetEtag sets field value
func (o *DriveReadOut) SetEtag(v string) {
	o.Etag = v
}

// GetId returns the Id field value
func (o *DriveReadOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DriveReadOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DriveReadOut) SetId(v string) {
	o.Id = v
}

// GetMetageneration returns the Metageneration field value
func (o *DriveReadOut) GetMetageneration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Metageneration
}

// GetMetagenerationOk returns a tuple with the Metageneration field value
// and a boolean to check if the value has been set.
func (o *DriveReadOut) GetMetagenerationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metageneration, true
}

// SetMetageneration sets field value
func (o *DriveReadOut) SetMetageneration(v int32) {
	o.Metageneration = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *DriveReadOut) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *DriveReadOut) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *DriveReadOut) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetStorageBytes returns the StorageBytes field value
func (o *DriveReadOut) GetStorageBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StorageBytes
}

// GetStorageBytesOk returns a tuple with the StorageBytes field value
// and a boolean to check if the value has been set.
func (o *DriveReadOut) GetStorageBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageBytes, true
}

// SetStorageBytes sets field value
func (o *DriveReadOut) SetStorageBytes(v int32) {
	o.StorageBytes = v
}

// GetStorageLimit returns the StorageLimit field value
func (o *DriveReadOut) GetStorageLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StorageLimit
}

// GetStorageLimitOk returns a tuple with the StorageLimit field value
// and a boolean to check if the value has been set.
func (o *DriveReadOut) GetStorageLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageLimit, true
}

// SetStorageLimit sets field value
func (o *DriveReadOut) SetStorageLimit(v int32) {
	o.StorageLimit = v
}

func (o DriveReadOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DriveReadOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	toSerialize["etag"] = o.Etag
	toSerialize["id"] = o.Id
	toSerialize["metageneration"] = o.Metageneration
	toSerialize["organization_id"] = o.OrganizationId
	toSerialize["storage_bytes"] = o.StorageBytes
	toSerialize["storage_limit"] = o.StorageLimit
	return toSerialize, nil
}

func (o *DriveReadOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"etag",
		"id",
		"metageneration",
		"organization_id",
		"storage_bytes",
		"storage_limit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDriveReadOut := _DriveReadOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDriveReadOut)

	if err != nil {
		return err
	}

	*o = DriveReadOut(varDriveReadOut)

	return err
}

type NullableDriveReadOut struct {
	value *DriveReadOut
	isSet bool
}

func (v NullableDriveReadOut) Get() *DriveReadOut {
	return v.value
}

func (v *NullableDriveReadOut) Set(val *DriveReadOut) {
	v.value = val
	v.isSet = true
}

func (v NullableDriveReadOut) IsSet() bool {
	return v.isSet
}

func (v *NullableDriveReadOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDriveReadOut(val *DriveReadOut) *NullableDriveReadOut {
	return &NullableDriveReadOut{value: val, isSet: true}
}

func (v NullableDriveReadOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDriveReadOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
