/*
AgentDrive

AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
)

// checks if the ValidationErrorResponseErrorDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationErrorResponseErrorDetails{}

// ValidationErrorResponseErrorDetails struct for ValidationErrorResponseErrorDetails
type ValidationErrorResponseErrorDetails struct {
	Fields []ValidationErrorResponseErrorDetailsFieldsInner `json:"fields,omitempty"`
}

// NewValidationErrorResponseErrorDetails instantiates a new ValidationErrorResponseErrorDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidationErrorResponseErrorDetails() *ValidationErrorResponseErrorDetails {
	this := ValidationErrorResponseErrorDetails{}
	return &this
}

// NewValidationErrorResponseErrorDetailsWithDefaults instantiates a new ValidationErrorResponseErrorDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationErrorResponseErrorDetailsWithDefaults() *ValidationErrorResponseErrorDetails {
	this := ValidationErrorResponseErrorDetails{}
	return &this
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *ValidationErrorResponseErrorDetails) GetFields() []ValidationErrorResponseErrorDetailsFieldsInner {
	if o == nil || IsNil(o.Fields) {
		var ret []ValidationErrorResponseErrorDetailsFieldsInner
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationErrorResponseErrorDetails) GetFieldsOk() ([]ValidationErrorResponseErrorDetailsFieldsInner, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *ValidationErrorResponseErrorDetails) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []ValidationErrorResponseErrorDetailsFieldsInner and assigns it to the Fields field.
func (o *ValidationErrorResponseErrorDetails) SetFields(v []ValidationErrorResponseErrorDetailsFieldsInner) {
	o.Fields = v
}

func (o ValidationErrorResponseErrorDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationErrorResponseErrorDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	return toSerialize, nil
}

type NullableValidationErrorResponseErrorDetails struct {
	value *ValidationErrorResponseErrorDetails
	isSet bool
}

func (v NullableValidationErrorResponseErrorDetails) Get() *ValidationErrorResponseErrorDetails {
	return v.value
}

func (v *NullableValidationErrorResponseErrorDetails) Set(val *ValidationErrorResponseErrorDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationErrorResponseErrorDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationErrorResponseErrorDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationErrorResponseErrorDetails(val *ValidationErrorResponseErrorDetails) *NullableValidationErrorResponseErrorDetails {
	return &NullableValidationErrorResponseErrorDetails{value: val, isSet: true}
}

func (v NullableValidationErrorResponseErrorDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationErrorResponseErrorDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


