/*
AgentDrive

AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"fmt"
)

// checks if the FolderCreateIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FolderCreateIn{}

// FolderCreateIn POST /v0/drives/{id}/folders body.
type FolderCreateIn struct {
	ParentId string `json:"parent_id" validate:"regexp=^fld_[a-f0-9]{16}$"`
	Name string `json:"name"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FolderCreateIn FolderCreateIn

// NewFolderCreateIn instantiates a new FolderCreateIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFolderCreateIn(parentId string, name string) *FolderCreateIn {
	this := FolderCreateIn{}
	this.ParentId = parentId
	this.Name = name
	return &this
}

// NewFolderCreateInWithDefaults instantiates a new FolderCreateIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFolderCreateInWithDefaults() *FolderCreateIn {
	this := FolderCreateIn{}
	return &this
}

// GetParentId returns the ParentId field value
func (o *FolderCreateIn) GetParentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value
// and a boolean to check if the value has been set.
func (o *FolderCreateIn) GetParentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentId, true
}

// SetParentId sets field value
func (o *FolderCreateIn) SetParentId(v string) {
	o.ParentId = v
}

// GetName returns the Name field value
func (o *FolderCreateIn) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FolderCreateIn) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FolderCreateIn) SetName(v string) {
	o.Name = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *FolderCreateIn) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FolderCreateIn) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *FolderCreateIn) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *FolderCreateIn) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o FolderCreateIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FolderCreateIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["parent_id"] = o.ParentId
	toSerialize["name"] = o.Name
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FolderCreateIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"parent_id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFolderCreateIn := _FolderCreateIn{}

	err = json.Unmarshal(data, &varFolderCreateIn)

	if err != nil {
		return err
	}

	*o = FolderCreateIn(varFolderCreateIn)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "parent_id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFolderCreateIn struct {
	value *FolderCreateIn
	isSet bool
}

func (v NullableFolderCreateIn) Get() *FolderCreateIn {
	return v.value
}

func (v *NullableFolderCreateIn) Set(val *FolderCreateIn) {
	v.value = val
	v.isSet = true
}

func (v NullableFolderCreateIn) IsSet() bool {
	return v.isSet
}

func (v *NullableFolderCreateIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFolderCreateIn(val *FolderCreateIn) *NullableFolderCreateIn {
	return &NullableFolderCreateIn{value: val, isSet: true}
}

func (v NullableFolderCreateIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFolderCreateIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


