/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: <PINNED>
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ClaimInitResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClaimInitResponse{}

// ClaimInitResponse struct for ClaimInitResponse
type ClaimInitResponse struct {
	// Per-attempt opaque token; the agent does not need to present it.
	ClaimAttemptToken string `json:"claim_attempt_token"`
	ExpiresAt time.Time `json:"expires_at"`
	// Human-readable code the user types/sees on /claim.
	UserCode string `json:"user_code"`
	// URL to direct the human to.
	VerificationUri string `json:"verification_uri"`
	// Convenience: same as `verification_uri` but with the user_code pre-baked so the human doesn't have to type it. RFC 8628 idiom.
	VerificationUriComplete string `json:"verification_uri_complete"`
}

type _ClaimInitResponse ClaimInitResponse

// NewClaimInitResponse instantiates a new ClaimInitResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClaimInitResponse(claimAttemptToken string, expiresAt time.Time, userCode string, verificationUri string, verificationUriComplete string) *ClaimInitResponse {
	this := ClaimInitResponse{}
	this.ClaimAttemptToken = claimAttemptToken
	this.ExpiresAt = expiresAt
	this.UserCode = userCode
	this.VerificationUri = verificationUri
	this.VerificationUriComplete = verificationUriComplete
	return &this
}

// NewClaimInitResponseWithDefaults instantiates a new ClaimInitResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClaimInitResponseWithDefaults() *ClaimInitResponse {
	this := ClaimInitResponse{}
	return &this
}

// GetClaimAttemptToken returns the ClaimAttemptToken field value
func (o *ClaimInitResponse) GetClaimAttemptToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClaimAttemptToken
}

// GetClaimAttemptTokenOk returns a tuple with the ClaimAttemptToken field value
// and a boolean to check if the value has been set.
func (o *ClaimInitResponse) GetClaimAttemptTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClaimAttemptToken, true
}

// SetClaimAttemptToken sets field value
func (o *ClaimInitResponse) SetClaimAttemptToken(v string) {
	o.ClaimAttemptToken = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *ClaimInitResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *ClaimInitResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *ClaimInitResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetUserCode returns the UserCode field value
func (o *ClaimInitResponse) GetUserCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserCode
}

// GetUserCodeOk returns a tuple with the UserCode field value
// and a boolean to check if the value has been set.
func (o *ClaimInitResponse) GetUserCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserCode, true
}

// SetUserCode sets field value
func (o *ClaimInitResponse) SetUserCode(v string) {
	o.UserCode = v
}

// GetVerificationUri returns the VerificationUri field value
func (o *ClaimInitResponse) GetVerificationUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationUri
}

// GetVerificationUriOk returns a tuple with the VerificationUri field value
// and a boolean to check if the value has been set.
func (o *ClaimInitResponse) GetVerificationUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationUri, true
}

// SetVerificationUri sets field value
func (o *ClaimInitResponse) SetVerificationUri(v string) {
	o.VerificationUri = v
}

// GetVerificationUriComplete returns the VerificationUriComplete field value
func (o *ClaimInitResponse) GetVerificationUriComplete() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationUriComplete
}

// GetVerificationUriCompleteOk returns a tuple with the VerificationUriComplete field value
// and a boolean to check if the value has been set.
func (o *ClaimInitResponse) GetVerificationUriCompleteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationUriComplete, true
}

// SetVerificationUriComplete sets field value
func (o *ClaimInitResponse) SetVerificationUriComplete(v string) {
	o.VerificationUriComplete = v
}

func (o ClaimInitResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClaimInitResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["claim_attempt_token"] = o.ClaimAttemptToken
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["user_code"] = o.UserCode
	toSerialize["verification_uri"] = o.VerificationUri
	toSerialize["verification_uri_complete"] = o.VerificationUriComplete
	return toSerialize, nil
}

func (o *ClaimInitResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"claim_attempt_token",
		"expires_at",
		"user_code",
		"verification_uri",
		"verification_uri_complete",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClaimInitResponse := _ClaimInitResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClaimInitResponse)

	if err != nil {
		return err
	}

	*o = ClaimInitResponse(varClaimInitResponse)

	return err
}

type NullableClaimInitResponse struct {
	value *ClaimInitResponse
	isSet bool
}

func (v NullableClaimInitResponse) Get() *ClaimInitResponse {
	return v.value
}

func (v *NullableClaimInitResponse) Set(val *ClaimInitResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClaimInitResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClaimInitResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClaimInitResponse(val *ClaimInitResponse) *NullableClaimInitResponse {
	return &NullableClaimInitResponse{value: val, isSet: true}
}

func (v NullableClaimInitResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClaimInitResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
