/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: <PINNED>
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ShareOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShareOut{}

// ShareOut A live share link as seen on list/management — NEVER carries the `share_key` (that is the credential, returned only at mint/rotate).
type ShareOut struct {
	AccessCount *int32 `json:"access_count,omitempty"`
	Audience string `json:"audience"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt NullableTime `json:"expires_at,omitempty"`
	HasPassword bool `json:"has_password"`
	Id string `json:"id"`
	LastAccessedAt NullableTime `json:"last_accessed_at,omitempty"`
	ResourceId string `json:"resource_id"`
	ResourceType string `json:"resource_type"`
	Role string `json:"role"`
}

type _ShareOut ShareOut

// NewShareOut instantiates a new ShareOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShareOut(audience string, createdAt time.Time, hasPassword bool, id string, resourceId string, resourceType string, role string) *ShareOut {
	this := ShareOut{}
	var accessCount int32 = 0
	this.AccessCount = &accessCount
	this.Audience = audience
	this.CreatedAt = createdAt
	this.HasPassword = hasPassword
	this.Id = id
	this.ResourceId = resourceId
	this.ResourceType = resourceType
	this.Role = role
	return &this
}

// NewShareOutWithDefaults instantiates a new ShareOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShareOutWithDefaults() *ShareOut {
	this := ShareOut{}
	var accessCount int32 = 0
	this.AccessCount = &accessCount
	return &this
}

// GetAccessCount returns the AccessCount field value if set, zero value otherwise.
func (o *ShareOut) GetAccessCount() int32 {
	if o == nil || IsNil(o.AccessCount) {
		var ret int32
		return ret
	}
	return *o.AccessCount
}

// GetAccessCountOk returns a tuple with the AccessCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShareOut) GetAccessCountOk() (*int32, bool) {
	if o == nil || IsNil(o.AccessCount) {
		return nil, false
	}
	return o.AccessCount, true
}

// HasAccessCount returns a boolean if a field has been set.
func (o *ShareOut) HasAccessCount() bool {
	if o != nil && !IsNil(o.AccessCount) {
		return true
	}

	return false
}

// SetAccessCount gets a reference to the given int32 and assigns it to the AccessCount field.
func (o *ShareOut) SetAccessCount(v int32) {
	o.AccessCount = &v
}

// GetAudience returns the Audience field value
func (o *ShareOut) GetAudience() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Audience
}

// GetAudienceOk returns a tuple with the Audience field value
// and a boolean to check if the value has been set.
func (o *ShareOut) GetAudienceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Audience, true
}

// SetAudience sets field value
func (o *ShareOut) SetAudience(v string) {
	o.Audience = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ShareOut) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ShareOut) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ShareOut) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShareOut) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShareOut) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *ShareOut) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *ShareOut) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *ShareOut) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *ShareOut) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetHasPassword returns the HasPassword field value
func (o *ShareOut) GetHasPassword() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasPassword
}

// GetHasPasswordOk returns a tuple with the HasPassword field value
// and a boolean to check if the value has been set.
func (o *ShareOut) GetHasPasswordOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasPassword, true
}

// SetHasPassword sets field value
func (o *ShareOut) SetHasPassword(v bool) {
	o.HasPassword = v
}

// GetId returns the Id field value
func (o *ShareOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ShareOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ShareOut) SetId(v string) {
	o.Id = v
}

// GetLastAccessedAt returns the LastAccessedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShareOut) GetLastAccessedAt() time.Time {
	if o == nil || IsNil(o.LastAccessedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastAccessedAt.Get()
}

// GetLastAccessedAtOk returns a tuple with the LastAccessedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShareOut) GetLastAccessedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastAccessedAt.Get(), o.LastAccessedAt.IsSet()
}

// HasLastAccessedAt returns a boolean if a field has been set.
func (o *ShareOut) HasLastAccessedAt() bool {
	if o != nil && o.LastAccessedAt.IsSet() {
		return true
	}

	return false
}

// SetLastAccessedAt gets a reference to the given NullableTime and assigns it to the LastAccessedAt field.
func (o *ShareOut) SetLastAccessedAt(v time.Time) {
	o.LastAccessedAt.Set(&v)
}
// SetLastAccessedAtNil sets the value for LastAccessedAt to be an explicit nil
func (o *ShareOut) SetLastAccessedAtNil() {
	o.LastAccessedAt.Set(nil)
}

// UnsetLastAccessedAt ensures that no value is present for LastAccessedAt, not even an explicit nil
func (o *ShareOut) UnsetLastAccessedAt() {
	o.LastAccessedAt.Unset()
}

// GetResourceId returns the ResourceId field value
func (o *ShareOut) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *ShareOut) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *ShareOut) SetResourceId(v string) {
	o.ResourceId = v
}

// GetResourceType returns the ResourceType field value
func (o *ShareOut) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *ShareOut) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *ShareOut) SetResourceType(v string) {
	o.ResourceType = v
}

// GetRole returns the Role field value
func (o *ShareOut) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ShareOut) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ShareOut) SetRole(v string) {
	o.Role = v
}

func (o ShareOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShareOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessCount) {
		toSerialize["access_count"] = o.AccessCount
	}
	toSerialize["audience"] = o.Audience
	toSerialize["created_at"] = o.CreatedAt
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	toSerialize["has_password"] = o.HasPassword
	toSerialize["id"] = o.Id
	if o.LastAccessedAt.IsSet() {
		toSerialize["last_accessed_at"] = o.LastAccessedAt.Get()
	}
	toSerialize["resource_id"] = o.ResourceId
	toSerialize["resource_type"] = o.ResourceType
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *ShareOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"audience",
		"created_at",
		"has_password",
		"id",
		"resource_id",
		"resource_type",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShareOut := _ShareOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShareOut)

	if err != nil {
		return err
	}

	*o = ShareOut(varShareOut)

	return err
}

type NullableShareOut struct {
	value *ShareOut
	isSet bool
}

func (v NullableShareOut) Get() *ShareOut {
	return v.value
}

func (v *NullableShareOut) Set(val *ShareOut) {
	v.value = val
	v.isSet = true
}

func (v NullableShareOut) IsSet() bool {
	return v.isSet
}

func (v *NullableShareOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShareOut(val *ShareOut) *NullableShareOut {
	return &NullableShareOut{value: val, isSet: true}
}

func (v NullableShareOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShareOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
