/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DriveList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DriveList{}

// DriveList struct for DriveList
type DriveList struct {
	Items []DriveOut `json:"items"`
	NextCursor NullableString `json:"next_cursor,omitempty"`
}

type _DriveList DriveList

// NewDriveList instantiates a new DriveList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDriveList(items []DriveOut) *DriveList {
	this := DriveList{}
	this.Items = items
	return &this
}

// NewDriveListWithDefaults instantiates a new DriveList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDriveListWithDefaults() *DriveList {
	this := DriveList{}
	return &this
}

// GetItems returns the Items field value
func (o *DriveList) GetItems() []DriveOut {
	if o == nil {
		var ret []DriveOut
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *DriveList) GetItemsOk() ([]DriveOut, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *DriveList) SetItems(v []DriveOut) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DriveList) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DriveList) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *DriveList) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *DriveList) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}
// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *DriveList) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *DriveList) UnsetNextCursor() {
	o.NextCursor.Unset()
}

func (o DriveList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DriveList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	if o.NextCursor.IsSet() {
		toSerialize["next_cursor"] = o.NextCursor.Get()
	}
	return toSerialize, nil
}

func (o *DriveList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDriveList := _DriveList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDriveList)

	if err != nil {
		return err
	}

	*o = DriveList(varDriveList)

	return err
}

type NullableDriveList struct {
	value *DriveList
	isSet bool
}

func (v NullableDriveList) Get() *DriveList {
	return v.value
}

func (v *NullableDriveList) Set(val *DriveList) {
	v.value = val
	v.isSet = true
}

func (v NullableDriveList) IsSet() bool {
	return v.isSet
}

func (v *NullableDriveList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDriveList(val *DriveList) *NullableDriveList {
	return &NullableDriveList{value: val, isSet: true}
}

func (v NullableDriveList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDriveList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


