/*
AgentDrive

AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FolderListOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FolderListOut{}

// FolderListOut struct for FolderListOut
type FolderListOut struct {
	Items []FolderOut `json:"items"`
	NextCursor NullableString `json:"next_cursor"`
}

type _FolderListOut FolderListOut

// NewFolderListOut instantiates a new FolderListOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFolderListOut(items []FolderOut, nextCursor NullableString) *FolderListOut {
	this := FolderListOut{}
	this.Items = items
	this.NextCursor = nextCursor
	return &this
}

// NewFolderListOutWithDefaults instantiates a new FolderListOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFolderListOutWithDefaults() *FolderListOut {
	this := FolderListOut{}
	return &this
}

// GetItems returns the Items field value
func (o *FolderListOut) GetItems() []FolderOut {
	if o == nil {
		var ret []FolderOut
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *FolderListOut) GetItemsOk() ([]FolderOut, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *FolderListOut) SetItems(v []FolderOut) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value
// If the value is explicit nil, the zero value for string will be returned
func (o *FolderListOut) GetNextCursor() string {
	if o == nil || o.NextCursor.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FolderListOut) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// SetNextCursor sets field value
func (o *FolderListOut) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

func (o FolderListOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FolderListOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["next_cursor"] = o.NextCursor.Get()
	return toSerialize, nil
}

func (o *FolderListOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"next_cursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFolderListOut := _FolderListOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFolderListOut)

	if err != nil {
		return err
	}

	*o = FolderListOut(varFolderListOut)

	return err
}

type NullableFolderListOut struct {
	value *FolderListOut
	isSet bool
}

func (v NullableFolderListOut) Get() *FolderListOut {
	return v.value
}

func (v *NullableFolderListOut) Set(val *FolderListOut) {
	v.value = val
	v.isSet = true
}

func (v NullableFolderListOut) IsSet() bool {
	return v.isSet
}

func (v *NullableFolderListOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFolderListOut(val *FolderListOut) *NullableFolderListOut {
	return &NullableFolderListOut{value: val, isSet: true}
}

func (v NullableFolderListOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFolderListOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


