/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: <PINNED>
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DescribeIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DescribeIn{}

// DescribeIn struct for DescribeIn
type DescribeIn struct {
	Dataset string `json:"dataset"`
}

type _DescribeIn DescribeIn

// NewDescribeIn instantiates a new DescribeIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeIn(dataset string) *DescribeIn {
	this := DescribeIn{}
	this.Dataset = dataset
	return &this
}

// NewDescribeInWithDefaults instantiates a new DescribeIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeInWithDefaults() *DescribeIn {
	this := DescribeIn{}
	return &this
}

// GetDataset returns the Dataset field value
func (o *DescribeIn) GetDataset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dataset
}

// GetDatasetOk returns a tuple with the Dataset field value
// and a boolean to check if the value has been set.
func (o *DescribeIn) GetDatasetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dataset, true
}

// SetDataset sets field value
func (o *DescribeIn) SetDataset(v string) {
	o.Dataset = v
}

func (o DescribeIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dataset"] = o.Dataset
	return toSerialize, nil
}

func (o *DescribeIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dataset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDescribeIn := _DescribeIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDescribeIn)

	if err != nil {
		return err
	}

	*o = DescribeIn(varDescribeIn)

	return err
}

type NullableDescribeIn struct {
	value *DescribeIn
	isSet bool
}

func (v NullableDescribeIn) Get() *DescribeIn {
	return v.value
}

func (v *NullableDescribeIn) Set(val *DescribeIn) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeIn) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeIn(val *DescribeIn) *NullableDescribeIn {
	return &NullableDescribeIn{value: val, isSet: true}
}

func (v NullableDescribeIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
