/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: <PINNED>
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadBeginIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadBeginIn{}

// UploadBeginIn Body of `POST /v0/uploads` — the large-upload begin call (large-upload- design.md §5.1). All artifact decisions are frozen here; the subsequent GCS PUT carries only bytes, and `commit` carries only the `upload_id`.  `labels`/`metadata`/`source` omitted (null) ⇒ preserve the existing artifact's value at commit; present (incl. empty) ⇒ replace.
type UploadBeginIn struct {
	ActorName NullableString `json:"actor_name,omitempty"`
	ChangeSummary NullableString `json:"change_summary,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
	// Web origin (scheme://host[:port]) of the browser that will PUT the bytes, e.g. `https://app.example.com`. Set this when the `upload_url` is handed to browser code: GCS binds CORS at session initiate, so the returned session only echoes `Access-Control-Allow-Origin` (and is thus PUT-able from a browser) when opened with the caller's origin. A trusted backend relaying a browser upload forwards the browser's `Origin` here. Omit for server/desktop uploads (no CORS enforcement).
	CorsOrigin NullableString `json:"cors_origin,omitempty"`
	Crc32c NullableString `json:"crc32c,omitempty"`
	IfMatch NullableInt32 `json:"if_match,omitempty"`
	IfNoneMatch *bool `json:"if_none_match,omitempty"`
	Labels []string `json:"labels,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Path string `json:"path"`
	SizeBytes int32 `json:"size_bytes"`
	Source NullableArtifactSource `json:"source,omitempty"`
}

type _UploadBeginIn UploadBeginIn

// NewUploadBeginIn instantiates a new UploadBeginIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadBeginIn(path string, sizeBytes int32) *UploadBeginIn {
	this := UploadBeginIn{}
	var contentType string = "application/octet-stream"
	this.ContentType = &contentType
	var ifNoneMatch bool = false
	this.IfNoneMatch = &ifNoneMatch
	this.Path = path
	this.SizeBytes = sizeBytes
	return &this
}

// NewUploadBeginInWithDefaults instantiates a new UploadBeginIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadBeginInWithDefaults() *UploadBeginIn {
	this := UploadBeginIn{}
	var contentType string = "application/octet-stream"
	this.ContentType = &contentType
	var ifNoneMatch bool = false
	this.IfNoneMatch = &ifNoneMatch
	return &this
}

// GetActorName returns the ActorName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UploadBeginIn) GetActorName() string {
	if o == nil || IsNil(o.ActorName.Get()) {
		var ret string
		return ret
	}
	return *o.ActorName.Get()
}

// GetActorNameOk returns a tuple with the ActorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UploadBeginIn) GetActorNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActorName.Get(), o.ActorName.IsSet()
}

// HasActorName returns a boolean if a field has been set.
func (o *UploadBeginIn) HasActorName() bool {
	if o != nil && o.ActorName.IsSet() {
		return true
	}

	return false
}

// SetActorName gets a reference to the given NullableString and assigns it to the ActorName field.
func (o *UploadBeginIn) SetActorName(v string) {
	o.ActorName.Set(&v)
}
// SetActorNameNil sets the value for ActorName to be an explicit nil
func (o *UploadBeginIn) SetActorNameNil() {
	o.ActorName.Set(nil)
}

// UnsetActorName ensures that no value is present for ActorName, not even an explicit nil
func (o *UploadBeginIn) UnsetActorName() {
	o.ActorName.Unset()
}

// GetChangeSummary returns the ChangeSummary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UploadBeginIn) GetChangeSummary() string {
	if o == nil || IsNil(o.ChangeSummary.Get()) {
		var ret string
		return ret
	}
	return *o.ChangeSummary.Get()
}

// GetChangeSummaryOk returns a tuple with the ChangeSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UploadBeginIn) GetChangeSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChangeSummary.Get(), o.ChangeSummary.IsSet()
}

// HasChangeSummary returns a boolean if a field has been set.
func (o *UploadBeginIn) HasChangeSummary() bool {
	if o != nil && o.ChangeSummary.IsSet() {
		return true
	}

	return false
}

// SetChangeSummary gets a reference to the given NullableString and assigns it to the ChangeSummary field.
func (o *UploadBeginIn) SetChangeSummary(v string) {
	o.ChangeSummary.Set(&v)
}
// SetChangeSummaryNil sets the value for ChangeSummary to be an explicit nil
func (o *UploadBeginIn) SetChangeSummaryNil() {
	o.ChangeSummary.Set(nil)
}

// UnsetChangeSummary ensures that no value is present for ChangeSummary, not even an explicit nil
func (o *UploadBeginIn) UnsetChangeSummary() {
	o.ChangeSummary.Unset()
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *UploadBeginIn) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadBeginIn) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *UploadBeginIn) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *UploadBeginIn) SetContentType(v string) {
	o.ContentType = &v
}

// GetCorsOrigin returns the CorsOrigin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UploadBeginIn) GetCorsOrigin() string {
	if o == nil || IsNil(o.CorsOrigin.Get()) {
		var ret string
		return ret
	}
	return *o.CorsOrigin.Get()
}

// GetCorsOriginOk returns a tuple with the CorsOrigin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UploadBeginIn) GetCorsOriginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CorsOrigin.Get(), o.CorsOrigin.IsSet()
}

// HasCorsOrigin returns a boolean if a field has been set.
func (o *UploadBeginIn) HasCorsOrigin() bool {
	if o != nil && o.CorsOrigin.IsSet() {
		return true
	}

	return false
}

// SetCorsOrigin gets a reference to the given NullableString and assigns it to the CorsOrigin field.
func (o *UploadBeginIn) SetCorsOrigin(v string) {
	o.CorsOrigin.Set(&v)
}
// SetCorsOriginNil sets the value for CorsOrigin to be an explicit nil
func (o *UploadBeginIn) SetCorsOriginNil() {
	o.CorsOrigin.Set(nil)
}

// UnsetCorsOrigin ensures that no value is present for CorsOrigin, not even an explicit nil
func (o *UploadBeginIn) UnsetCorsOrigin() {
	o.CorsOrigin.Unset()
}

// GetCrc32c returns the Crc32c field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UploadBeginIn) GetCrc32c() string {
	if o == nil || IsNil(o.Crc32c.Get()) {
		var ret string
		return ret
	}
	return *o.Crc32c.Get()
}

// GetCrc32cOk returns a tuple with the Crc32c field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UploadBeginIn) GetCrc32cOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Crc32c.Get(), o.Crc32c.IsSet()
}

// HasCrc32c returns a boolean if a field has been set.
func (o *UploadBeginIn) HasCrc32c() bool {
	if o != nil && o.Crc32c.IsSet() {
		return true
	}

	return false
}

// SetCrc32c gets a reference to the given NullableString and assigns it to the Crc32c field.
func (o *UploadBeginIn) SetCrc32c(v string) {
	o.Crc32c.Set(&v)
}
// SetCrc32cNil sets the value for Crc32c to be an explicit nil
func (o *UploadBeginIn) SetCrc32cNil() {
	o.Crc32c.Set(nil)
}

// UnsetCrc32c ensures that no value is present for Crc32c, not even an explicit nil
func (o *UploadBeginIn) UnsetCrc32c() {
	o.Crc32c.Unset()
}

// GetIfMatch returns the IfMatch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UploadBeginIn) GetIfMatch() int32 {
	if o == nil || IsNil(o.IfMatch.Get()) {
		var ret int32
		return ret
	}
	return *o.IfMatch.Get()
}

// GetIfMatchOk returns a tuple with the IfMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UploadBeginIn) GetIfMatchOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.IfMatch.Get(), o.IfMatch.IsSet()
}

// HasIfMatch returns a boolean if a field has been set.
func (o *UploadBeginIn) HasIfMatch() bool {
	if o != nil && o.IfMatch.IsSet() {
		return true
	}

	return false
}

// SetIfMatch gets a reference to the given NullableInt32 and assigns it to the IfMatch field.
func (o *UploadBeginIn) SetIfMatch(v int32) {
	o.IfMatch.Set(&v)
}
// SetIfMatchNil sets the value for IfMatch to be an explicit nil
func (o *UploadBeginIn) SetIfMatchNil() {
	o.IfMatch.Set(nil)
}

// UnsetIfMatch ensures that no value is present for IfMatch, not even an explicit nil
func (o *UploadBeginIn) UnsetIfMatch() {
	o.IfMatch.Unset()
}

// GetIfNoneMatch returns the IfNoneMatch field value if set, zero value otherwise.
func (o *UploadBeginIn) GetIfNoneMatch() bool {
	if o == nil || IsNil(o.IfNoneMatch) {
		var ret bool
		return ret
	}
	return *o.IfNoneMatch
}

// GetIfNoneMatchOk returns a tuple with the IfNoneMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadBeginIn) GetIfNoneMatchOk() (*bool, bool) {
	if o == nil || IsNil(o.IfNoneMatch) {
		return nil, false
	}
	return o.IfNoneMatch, true
}

// HasIfNoneMatch returns a boolean if a field has been set.
func (o *UploadBeginIn) HasIfNoneMatch() bool {
	if o != nil && !IsNil(o.IfNoneMatch) {
		return true
	}

	return false
}

// SetIfNoneMatch gets a reference to the given bool and assigns it to the IfNoneMatch field.
func (o *UploadBeginIn) SetIfNoneMatch(v bool) {
	o.IfNoneMatch = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UploadBeginIn) GetLabels() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UploadBeginIn) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *UploadBeginIn) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *UploadBeginIn) SetLabels(v []string) {
	o.Labels = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UploadBeginIn) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UploadBeginIn) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *UploadBeginIn) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *UploadBeginIn) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetPath returns the Path field value
func (o *UploadBeginIn) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *UploadBeginIn) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *UploadBeginIn) SetPath(v string) {
	o.Path = v
}

// GetSizeBytes returns the SizeBytes field value
func (o *UploadBeginIn) GetSizeBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SizeBytes
}

// GetSizeBytesOk returns a tuple with the SizeBytes field value
// and a boolean to check if the value has been set.
func (o *UploadBeginIn) GetSizeBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SizeBytes, true
}

// SetSizeBytes sets field value
func (o *UploadBeginIn) SetSizeBytes(v int32) {
	o.SizeBytes = v
}

// GetSource returns the Source field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UploadBeginIn) GetSource() ArtifactSource {
	if o == nil || IsNil(o.Source.Get()) {
		var ret ArtifactSource
		return ret
	}
	return *o.Source.Get()
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UploadBeginIn) GetSourceOk() (*ArtifactSource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Source.Get(), o.Source.IsSet()
}

// HasSource returns a boolean if a field has been set.
func (o *UploadBeginIn) HasSource() bool {
	if o != nil && o.Source.IsSet() {
		return true
	}

	return false
}

// SetSource gets a reference to the given NullableArtifactSource and assigns it to the Source field.
func (o *UploadBeginIn) SetSource(v ArtifactSource) {
	o.Source.Set(&v)
}
// SetSourceNil sets the value for Source to be an explicit nil
func (o *UploadBeginIn) SetSourceNil() {
	o.Source.Set(nil)
}

// UnsetSource ensures that no value is present for Source, not even an explicit nil
func (o *UploadBeginIn) UnsetSource() {
	o.Source.Unset()
}

func (o UploadBeginIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadBeginIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ActorName.IsSet() {
		toSerialize["actor_name"] = o.ActorName.Get()
	}
	if o.ChangeSummary.IsSet() {
		toSerialize["change_summary"] = o.ChangeSummary.Get()
	}
	if !IsNil(o.ContentType) {
		toSerialize["content_type"] = o.ContentType
	}
	if o.CorsOrigin.IsSet() {
		toSerialize["cors_origin"] = o.CorsOrigin.Get()
	}
	if o.Crc32c.IsSet() {
		toSerialize["crc32c"] = o.Crc32c.Get()
	}
	if o.IfMatch.IsSet() {
		toSerialize["if_match"] = o.IfMatch.Get()
	}
	if !IsNil(o.IfNoneMatch) {
		toSerialize["if_none_match"] = o.IfNoneMatch
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["path"] = o.Path
	toSerialize["size_bytes"] = o.SizeBytes
	if o.Source.IsSet() {
		toSerialize["source"] = o.Source.Get()
	}
	return toSerialize, nil
}

func (o *UploadBeginIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
		"size_bytes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadBeginIn := _UploadBeginIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadBeginIn)

	if err != nil {
		return err
	}

	*o = UploadBeginIn(varUploadBeginIn)

	return err
}

type NullableUploadBeginIn struct {
	value *UploadBeginIn
	isSet bool
}

func (v NullableUploadBeginIn) Get() *UploadBeginIn {
	return v.value
}

func (v *NullableUploadBeginIn) Set(val *UploadBeginIn) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadBeginIn) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadBeginIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadBeginIn(val *UploadBeginIn) *NullableUploadBeginIn {
	return &NullableUploadBeginIn{value: val, isSet: true}
}

func (v NullableUploadBeginIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadBeginIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
