/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the InvitationOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvitationOut{}

// InvitationOut One workspace invitation — metadata only; the raw token is never surfaced over the API (it lives only in the invite email).
type InvitationOut struct {
	Id string `json:"id"`
	OrganizationId string `json:"organization_id"`
	Email string `json:"email"`
	Role string `json:"role"`
	Status string `json:"status"`
	InvitedBy NullableString `json:"invited_by,omitempty"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type _InvitationOut InvitationOut

// NewInvitationOut instantiates a new InvitationOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvitationOut(id string, organizationId string, email string, role string, status string, expiresAt time.Time, createdAt time.Time) *InvitationOut {
	this := InvitationOut{}
	this.Id = id
	this.OrganizationId = organizationId
	this.Email = email
	this.Role = role
	this.Status = status
	this.ExpiresAt = expiresAt
	this.CreatedAt = createdAt
	return &this
}

// NewInvitationOutWithDefaults instantiates a new InvitationOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvitationOutWithDefaults() *InvitationOut {
	this := InvitationOut{}
	return &this
}

// GetId returns the Id field value
func (o *InvitationOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *InvitationOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *InvitationOut) SetId(v string) {
	o.Id = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *InvitationOut) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *InvitationOut) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *InvitationOut) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetEmail returns the Email field value
func (o *InvitationOut) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *InvitationOut) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *InvitationOut) SetEmail(v string) {
	o.Email = v
}

// GetRole returns the Role field value
func (o *InvitationOut) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *InvitationOut) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *InvitationOut) SetRole(v string) {
	o.Role = v
}

// GetStatus returns the Status field value
func (o *InvitationOut) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *InvitationOut) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *InvitationOut) SetStatus(v string) {
	o.Status = v
}

// GetInvitedBy returns the InvitedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InvitationOut) GetInvitedBy() string {
	if o == nil || IsNil(o.InvitedBy.Get()) {
		var ret string
		return ret
	}
	return *o.InvitedBy.Get()
}

// GetInvitedByOk returns a tuple with the InvitedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InvitationOut) GetInvitedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InvitedBy.Get(), o.InvitedBy.IsSet()
}

// HasInvitedBy returns a boolean if a field has been set.
func (o *InvitationOut) HasInvitedBy() bool {
	if o != nil && o.InvitedBy.IsSet() {
		return true
	}

	return false
}

// SetInvitedBy gets a reference to the given NullableString and assigns it to the InvitedBy field.
func (o *InvitationOut) SetInvitedBy(v string) {
	o.InvitedBy.Set(&v)
}
// SetInvitedByNil sets the value for InvitedBy to be an explicit nil
func (o *InvitationOut) SetInvitedByNil() {
	o.InvitedBy.Set(nil)
}

// UnsetInvitedBy ensures that no value is present for InvitedBy, not even an explicit nil
func (o *InvitationOut) UnsetInvitedBy() {
	o.InvitedBy.Unset()
}

// GetExpiresAt returns the ExpiresAt field value
func (o *InvitationOut) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *InvitationOut) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *InvitationOut) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *InvitationOut) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *InvitationOut) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *InvitationOut) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o InvitationOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvitationOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["organization_id"] = o.OrganizationId
	toSerialize["email"] = o.Email
	toSerialize["role"] = o.Role
	toSerialize["status"] = o.Status
	if o.InvitedBy.IsSet() {
		toSerialize["invited_by"] = o.InvitedBy.Get()
	}
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *InvitationOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"organization_id",
		"email",
		"role",
		"status",
		"expires_at",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvitationOut := _InvitationOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInvitationOut)

	if err != nil {
		return err
	}

	*o = InvitationOut(varInvitationOut)

	return err
}

type NullableInvitationOut struct {
	value *InvitationOut
	isSet bool
}

func (v NullableInvitationOut) Get() *InvitationOut {
	return v.value
}

func (v *NullableInvitationOut) Set(val *InvitationOut) {
	v.value = val
	v.isSet = true
}

func (v NullableInvitationOut) IsSet() bool {
	return v.isSet
}

func (v *NullableInvitationOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvitationOut(val *InvitationOut) *NullableInvitationOut {
	return &NullableInvitationOut{value: val, isSet: true}
}

func (v NullableInvitationOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvitationOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


