/*
AgentDrive

AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
)

// checks if the DriveUpdateIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DriveUpdateIn{}

// DriveUpdateIn PATCH /v0/drives/{id} body — at least one field is required.
type DriveUpdateIn struct {
	Name NullableString `json:"name,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DriveUpdateIn DriveUpdateIn

// NewDriveUpdateIn instantiates a new DriveUpdateIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDriveUpdateIn() *DriveUpdateIn {
	this := DriveUpdateIn{}
	return &this
}

// NewDriveUpdateInWithDefaults instantiates a new DriveUpdateIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDriveUpdateInWithDefaults() *DriveUpdateIn {
	this := DriveUpdateIn{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DriveUpdateIn) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DriveUpdateIn) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *DriveUpdateIn) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *DriveUpdateIn) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *DriveUpdateIn) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *DriveUpdateIn) UnsetName() {
	o.Name.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DriveUpdateIn) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DriveUpdateIn) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *DriveUpdateIn) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *DriveUpdateIn) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o DriveUpdateIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DriveUpdateIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DriveUpdateIn) UnmarshalJSON(data []byte) (err error) {
	varDriveUpdateIn := _DriveUpdateIn{}

	err = json.Unmarshal(data, &varDriveUpdateIn)

	if err != nil {
		return err
	}

	*o = DriveUpdateIn(varDriveUpdateIn)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDriveUpdateIn struct {
	value *DriveUpdateIn
	isSet bool
}

func (v NullableDriveUpdateIn) Get() *DriveUpdateIn {
	return v.value
}

func (v *NullableDriveUpdateIn) Set(val *DriveUpdateIn) {
	v.value = val
	v.isSet = true
}

func (v NullableDriveUpdateIn) IsSet() bool {
	return v.isSet
}

func (v *NullableDriveUpdateIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDriveUpdateIn(val *DriveUpdateIn) *NullableDriveUpdateIn {
	return &NullableDriveUpdateIn{value: val, isSet: true}
}

func (v NullableDriveUpdateIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDriveUpdateIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


