/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: <PINNED>
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClaimInitRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClaimInitRequest{}

// ClaimInitRequest `POST /agent/identity/claim` body.
type ClaimInitRequest struct {
	// The per-identity claim_token returned by POST /agent/identity.
	ClaimToken string `json:"claim_token"`
	// Optional hint to display on the /claim page so the human knows which account the agent expected. Not enforced (design §14 question #3).
	Email NullableString `json:"email,omitempty"`
}

type _ClaimInitRequest ClaimInitRequest

// NewClaimInitRequest instantiates a new ClaimInitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClaimInitRequest(claimToken string) *ClaimInitRequest {
	this := ClaimInitRequest{}
	this.ClaimToken = claimToken
	return &this
}

// NewClaimInitRequestWithDefaults instantiates a new ClaimInitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClaimInitRequestWithDefaults() *ClaimInitRequest {
	this := ClaimInitRequest{}
	return &this
}

// GetClaimToken returns the ClaimToken field value
func (o *ClaimInitRequest) GetClaimToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClaimToken
}

// GetClaimTokenOk returns a tuple with the ClaimToken field value
// and a boolean to check if the value has been set.
func (o *ClaimInitRequest) GetClaimTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClaimToken, true
}

// SetClaimToken sets field value
func (o *ClaimInitRequest) SetClaimToken(v string) {
	o.ClaimToken = v
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClaimInitRequest) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClaimInitRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *ClaimInitRequest) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *ClaimInitRequest) SetEmail(v string) {
	o.Email.Set(&v)
}
// SetEmailNil sets the value for Email to be an explicit nil
func (o *ClaimInitRequest) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *ClaimInitRequest) UnsetEmail() {
	o.Email.Unset()
}

func (o ClaimInitRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClaimInitRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["claim_token"] = o.ClaimToken
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	return toSerialize, nil
}

func (o *ClaimInitRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"claim_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClaimInitRequest := _ClaimInitRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClaimInitRequest)

	if err != nil {
		return err
	}

	*o = ClaimInitRequest(varClaimInitRequest)

	return err
}

type NullableClaimInitRequest struct {
	value *ClaimInitRequest
	isSet bool
}

func (v NullableClaimInitRequest) Get() *ClaimInitRequest {
	return v.value
}

func (v *NullableClaimInitRequest) Set(val *ClaimInitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClaimInitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClaimInitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClaimInitRequest(val *ClaimInitRequest) *NullableClaimInitRequest {
	return &NullableClaimInitRequest{value: val, isSet: true}
}

func (v NullableClaimInitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClaimInitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
