/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DriveCreateOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DriveCreateOut{}

// DriveCreateOut The create response — the ONLY place (besides key-rotate) a raw `ad_live_` key is returned, reveal-once.
type DriveCreateOut struct {
	Id string `json:"id"`
	Name string `json:"name"`
	OrganizationId string `json:"organization_id"`
	OwnerUserId NullableString `json:"owner_user_id,omitempty"`
	OwnerEmail NullableString `json:"owner_email,omitempty"`
	StorageBytes int32 `json:"storage_bytes"`
	CreatedAt time.Time `json:"created_at"`
	ApiKey string `json:"api_key"`
}

type _DriveCreateOut DriveCreateOut

// NewDriveCreateOut instantiates a new DriveCreateOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDriveCreateOut(id string, name string, organizationId string, storageBytes int32, createdAt time.Time, apiKey string) *DriveCreateOut {
	this := DriveCreateOut{}
	this.Id = id
	this.Name = name
	this.OrganizationId = organizationId
	this.StorageBytes = storageBytes
	this.CreatedAt = createdAt
	this.ApiKey = apiKey
	return &this
}

// NewDriveCreateOutWithDefaults instantiates a new DriveCreateOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDriveCreateOutWithDefaults() *DriveCreateOut {
	this := DriveCreateOut{}
	return &this
}

// GetId returns the Id field value
func (o *DriveCreateOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DriveCreateOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DriveCreateOut) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *DriveCreateOut) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DriveCreateOut) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DriveCreateOut) SetName(v string) {
	o.Name = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *DriveCreateOut) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *DriveCreateOut) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *DriveCreateOut) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetOwnerUserId returns the OwnerUserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DriveCreateOut) GetOwnerUserId() string {
	if o == nil || IsNil(o.OwnerUserId.Get()) {
		var ret string
		return ret
	}
	return *o.OwnerUserId.Get()
}

// GetOwnerUserIdOk returns a tuple with the OwnerUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DriveCreateOut) GetOwnerUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OwnerUserId.Get(), o.OwnerUserId.IsSet()
}

// HasOwnerUserId returns a boolean if a field has been set.
func (o *DriveCreateOut) HasOwnerUserId() bool {
	if o != nil && o.OwnerUserId.IsSet() {
		return true
	}

	return false
}

// SetOwnerUserId gets a reference to the given NullableString and assigns it to the OwnerUserId field.
func (o *DriveCreateOut) SetOwnerUserId(v string) {
	o.OwnerUserId.Set(&v)
}
// SetOwnerUserIdNil sets the value for OwnerUserId to be an explicit nil
func (o *DriveCreateOut) SetOwnerUserIdNil() {
	o.OwnerUserId.Set(nil)
}

// UnsetOwnerUserId ensures that no value is present for OwnerUserId, not even an explicit nil
func (o *DriveCreateOut) UnsetOwnerUserId() {
	o.OwnerUserId.Unset()
}

// GetOwnerEmail returns the OwnerEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DriveCreateOut) GetOwnerEmail() string {
	if o == nil || IsNil(o.OwnerEmail.Get()) {
		var ret string
		return ret
	}
	return *o.OwnerEmail.Get()
}

// GetOwnerEmailOk returns a tuple with the OwnerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DriveCreateOut) GetOwnerEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OwnerEmail.Get(), o.OwnerEmail.IsSet()
}

// HasOwnerEmail returns a boolean if a field has been set.
func (o *DriveCreateOut) HasOwnerEmail() bool {
	if o != nil && o.OwnerEmail.IsSet() {
		return true
	}

	return false
}

// SetOwnerEmail gets a reference to the given NullableString and assigns it to the OwnerEmail field.
func (o *DriveCreateOut) SetOwnerEmail(v string) {
	o.OwnerEmail.Set(&v)
}
// SetOwnerEmailNil sets the value for OwnerEmail to be an explicit nil
func (o *DriveCreateOut) SetOwnerEmailNil() {
	o.OwnerEmail.Set(nil)
}

// UnsetOwnerEmail ensures that no value is present for OwnerEmail, not even an explicit nil
func (o *DriveCreateOut) UnsetOwnerEmail() {
	o.OwnerEmail.Unset()
}

// GetStorageBytes returns the StorageBytes field value
func (o *DriveCreateOut) GetStorageBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StorageBytes
}

// GetStorageBytesOk returns a tuple with the StorageBytes field value
// and a boolean to check if the value has been set.
func (o *DriveCreateOut) GetStorageBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StorageBytes, true
}

// SetStorageBytes sets field value
func (o *DriveCreateOut) SetStorageBytes(v int32) {
	o.StorageBytes = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DriveCreateOut) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DriveCreateOut) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DriveCreateOut) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetApiKey returns the ApiKey field value
func (o *DriveCreateOut) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *DriveCreateOut) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *DriveCreateOut) SetApiKey(v string) {
	o.ApiKey = v
}

func (o DriveCreateOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DriveCreateOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["organization_id"] = o.OrganizationId
	if o.OwnerUserId.IsSet() {
		toSerialize["owner_user_id"] = o.OwnerUserId.Get()
	}
	if o.OwnerEmail.IsSet() {
		toSerialize["owner_email"] = o.OwnerEmail.Get()
	}
	toSerialize["storage_bytes"] = o.StorageBytes
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["api_key"] = o.ApiKey
	return toSerialize, nil
}

func (o *DriveCreateOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"organization_id",
		"storage_bytes",
		"created_at",
		"api_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDriveCreateOut := _DriveCreateOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDriveCreateOut)

	if err != nil {
		return err
	}

	*o = DriveCreateOut(varDriveCreateOut)

	return err
}

type NullableDriveCreateOut struct {
	value *DriveCreateOut
	isSet bool
}

func (v NullableDriveCreateOut) Get() *DriveCreateOut {
	return v.value
}

func (v *NullableDriveCreateOut) Set(val *DriveCreateOut) {
	v.value = val
	v.isSet = true
}

func (v NullableDriveCreateOut) IsSet() bool {
	return v.isSet
}

func (v *NullableDriveCreateOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDriveCreateOut(val *DriveCreateOut) *NullableDriveCreateOut {
	return &NullableDriveCreateOut{value: val, isSet: true}
}

func (v NullableDriveCreateOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDriveCreateOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


