/*
AgentDrive

AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.

API version: <PINNED>
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EntryListOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntryListOut{}

// EntryListOut struct for EntryListOut
type EntryListOut struct {
	Entries []EntriesInner `json:"entries"`
	NextCursor NullableString `json:"next_cursor"`
}

type _EntryListOut EntryListOut

// NewEntryListOut instantiates a new EntryListOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntryListOut(entries []EntriesInner, nextCursor NullableString) *EntryListOut {
	this := EntryListOut{}
	this.Entries = entries
	this.NextCursor = nextCursor
	return &this
}

// NewEntryListOutWithDefaults instantiates a new EntryListOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntryListOutWithDefaults() *EntryListOut {
	this := EntryListOut{}
	return &this
}

// GetEntries returns the Entries field value
func (o *EntryListOut) GetEntries() []EntriesInner {
	if o == nil {
		var ret []EntriesInner
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *EntryListOut) GetEntriesOk() ([]EntriesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *EntryListOut) SetEntries(v []EntriesInner) {
	o.Entries = v
}

// GetNextCursor returns the NextCursor field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EntryListOut) GetNextCursor() string {
	if o == nil || o.NextCursor.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntryListOut) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// SetNextCursor sets field value
func (o *EntryListOut) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

func (o EntryListOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntryListOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entries"] = o.Entries
	toSerialize["next_cursor"] = o.NextCursor.Get()
	return toSerialize, nil
}

func (o *EntryListOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entries",
		"next_cursor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntryListOut := _EntryListOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntryListOut)

	if err != nil {
		return err
	}

	*o = EntryListOut(varEntryListOut)

	return err
}

type NullableEntryListOut struct {
	value *EntryListOut
	isSet bool
}

func (v NullableEntryListOut) Get() *EntryListOut {
	return v.value
}

func (v *NullableEntryListOut) Set(val *EntryListOut) {
	v.value = val
	v.isSet = true
}

func (v NullableEntryListOut) IsSet() bool {
	return v.isSet
}

func (v *NullableEntryListOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntryListOut(val *EntryListOut) *NullableEntryListOut {
	return &NullableEntryListOut{value: val, isSet: true}
}

func (v NullableEntryListOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntryListOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
