/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: <PINNED>
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
)

// checks if the GrantPatchIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GrantPatchIn{}

// GrantPatchIn PATCH /v0/grants/{grn_id} body. Field absence = unchanged; explicit `expires_in: null` clears the expiry (makes the grant permanent).
type GrantPatchIn struct {
	ExpiresIn NullableInt32 `json:"expires_in,omitempty"`
	Role NullableString `json:"role,omitempty"`
}

// NewGrantPatchIn instantiates a new GrantPatchIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrantPatchIn() *GrantPatchIn {
	this := GrantPatchIn{}
	return &this
}

// NewGrantPatchInWithDefaults instantiates a new GrantPatchIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrantPatchInWithDefaults() *GrantPatchIn {
	this := GrantPatchIn{}
	return &this
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GrantPatchIn) GetExpiresIn() int32 {
	if o == nil || IsNil(o.ExpiresIn.Get()) {
		var ret int32
		return ret
	}
	return *o.ExpiresIn.Get()
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GrantPatchIn) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresIn.Get(), o.ExpiresIn.IsSet()
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *GrantPatchIn) HasExpiresIn() bool {
	if o != nil && o.ExpiresIn.IsSet() {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given NullableInt32 and assigns it to the ExpiresIn field.
func (o *GrantPatchIn) SetExpiresIn(v int32) {
	o.ExpiresIn.Set(&v)
}
// SetExpiresInNil sets the value for ExpiresIn to be an explicit nil
func (o *GrantPatchIn) SetExpiresInNil() {
	o.ExpiresIn.Set(nil)
}

// UnsetExpiresIn ensures that no value is present for ExpiresIn, not even an explicit nil
func (o *GrantPatchIn) UnsetExpiresIn() {
	o.ExpiresIn.Unset()
}

// GetRole returns the Role field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GrantPatchIn) GetRole() string {
	if o == nil || IsNil(o.Role.Get()) {
		var ret string
		return ret
	}
	return *o.Role.Get()
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GrantPatchIn) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Role.Get(), o.Role.IsSet()
}

// HasRole returns a boolean if a field has been set.
func (o *GrantPatchIn) HasRole() bool {
	if o != nil && o.Role.IsSet() {
		return true
	}

	return false
}

// SetRole gets a reference to the given NullableString and assigns it to the Role field.
func (o *GrantPatchIn) SetRole(v string) {
	o.Role.Set(&v)
}
// SetRoleNil sets the value for Role to be an explicit nil
func (o *GrantPatchIn) SetRoleNil() {
	o.Role.Set(nil)
}

// UnsetRole ensures that no value is present for Role, not even an explicit nil
func (o *GrantPatchIn) UnsetRole() {
	o.Role.Unset()
}

func (o GrantPatchIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GrantPatchIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ExpiresIn.IsSet() {
		toSerialize["expires_in"] = o.ExpiresIn.Get()
	}
	if o.Role.IsSet() {
		toSerialize["role"] = o.Role.Get()
	}
	return toSerialize, nil
}

type NullableGrantPatchIn struct {
	value *GrantPatchIn
	isSet bool
}

func (v NullableGrantPatchIn) Get() *GrantPatchIn {
	return v.value
}

func (v *NullableGrantPatchIn) Set(val *GrantPatchIn) {
	v.value = val
	v.isSet = true
}

func (v NullableGrantPatchIn) IsSet() bool {
	return v.isSet
}

func (v *NullableGrantPatchIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrantPatchIn(val *GrantPatchIn) *NullableGrantPatchIn {
	return &NullableGrantPatchIn{value: val, isSet: true}
}

func (v NullableGrantPatchIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrantPatchIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
