/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * Compact D13 artifact member; content and rich metadata stay excluded.
 * @export
 * @interface ArtifactEntryOut
 */
export interface ArtifactEntryOut {
    /**
     * 
     */
    type: ArtifactEntryOutTypeEnum;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    revision: string;
    /**
     * 
     */
    updatedAt: Date;
    /**
     * 
     */
    state: ArtifactEntryOutStateEnum;
    /**
     * 
     */
    deletedAt: Date | null;
    /**
     * 
     */
    sizeBytes: number;
    /**
     * 
     */
    contentType: string | null;
    /**
     * 
     */
    headVersionId: string | null;
}


/**
 * @export
 */
export const ArtifactEntryOutTypeEnum = {
    Artifact: 'artifact',
} as const;
export type ArtifactEntryOutTypeEnum = typeof ArtifactEntryOutTypeEnum[keyof typeof ArtifactEntryOutTypeEnum];

/**
 * @export
 */
export const ArtifactEntryOutStateEnum = {
    Active: 'active',
    Deleted: 'deleted',
} as const;
export type ArtifactEntryOutStateEnum = typeof ArtifactEntryOutStateEnum[keyof typeof ArtifactEntryOutStateEnum];


/**
 * Check if a given object implements the ArtifactEntryOut interface.
 */
export function instanceOfArtifactEntryOut(value: object): value is ArtifactEntryOut {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (value['type'] !== 'artifact') return false;
    
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if ((!('deletedAt' in (value as Record<string, any>)) && !('deleted_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['deletedAt'] === undefined && (value as Record<string, any>)['deleted_at'] === undefined)) return false;
    if ((!('sizeBytes' in (value as Record<string, any>)) && !('size_bytes' in (value as Record<string, any>))) || ((value as Record<string, any>)['sizeBytes'] === undefined && (value as Record<string, any>)['size_bytes'] === undefined)) return false;
    if ((!('contentType' in (value as Record<string, any>)) && !('content_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['contentType'] === undefined && (value as Record<string, any>)['content_type'] === undefined)) return false;
    if ((!('headVersionId' in (value as Record<string, any>)) && !('head_version_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['headVersionId'] === undefined && (value as Record<string, any>)['head_version_id'] === undefined)) return false;
    return true;
}

export function ArtifactEntryOutFromJSON(json: any): ArtifactEntryOut {
    return ArtifactEntryOutFromJSONTyped(json, false);
}

export function ArtifactEntryOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArtifactEntryOut {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'name': json['name'],
        'revision': json['revision'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
        'state': json['state'],
        'deletedAt': (json['deleted_at'] == null ? null : parseDateTime(json['deleted_at'])),
        'sizeBytes': json['size_bytes'],
        'contentType': json['content_type'],
        'headVersionId': json['head_version_id'],
    };
}

export function ArtifactEntryOutToJSON(json: any): ArtifactEntryOut {
    return ArtifactEntryOutToJSONTyped(json, false);
}

export function ArtifactEntryOutToJSONTyped(value?: ArtifactEntryOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'name': value['name'],
        'revision': value['revision'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
        'state': value['state'],
        'deleted_at': value['deletedAt'] == null ? value['deletedAt'] : serializeDateTime(value['deletedAt']),
        'size_bytes': value['sizeBytes'],
        'content_type': value['contentType'],
        'head_version_id': value['headVersionId'],
    };
}

