/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DownloadOut } from './DownloadOut';
import {
    DownloadOutFromJSON,
    DownloadOutFromJSONTyped,
    DownloadOutToJSON,
    DownloadOutToJSONTyped,
} from './DownloadOut';

/**
 * The §5.7 mint response — a capability computation, not a stored
 * resource: 200 only, freshly signed on every call.
 * @export
 * @interface DownloadCapabilityOut
 */
export interface DownloadCapabilityOut {
    /**
     * 
     */
    download: DownloadOut;
}

/**
 * Check if a given object implements the DownloadCapabilityOut interface.
 */
export function instanceOfDownloadCapabilityOut(value: object): value is DownloadCapabilityOut {
    if (!('download' in value) || value['download'] === undefined) return false;
    return true;
}

export function DownloadCapabilityOutFromJSON(json: any): DownloadCapabilityOut {
    return DownloadCapabilityOutFromJSONTyped(json, false);
}

export function DownloadCapabilityOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadCapabilityOut {
    if (json == null) {
        return json;
    }
    return {
        
        'download': DownloadOutFromJSON(json['download']),
    };
}

export function DownloadCapabilityOutToJSON(json: any): DownloadCapabilityOut {
    return DownloadCapabilityOutToJSONTyped(json, false);
}

export function DownloadCapabilityOutToJSONTyped(value?: DownloadCapabilityOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'download': DownloadOutToJSON(value['download']),
    };
}

