/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: <PINNED>
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DrivesCreate400ResponseError } from './DrivesCreate400ResponseError';
import {
    DrivesCreate400ResponseErrorFromJSON,
    DrivesCreate400ResponseErrorFromJSONTyped,
    DrivesCreate400ResponseErrorToJSON,
    DrivesCreate400ResponseErrorToJSONTyped,
} from './DrivesCreate400ResponseError';

/**
 *
 * @export
 * @interface DrivesCreate400Response
 */
export interface DrivesCreate400Response {
    /**
     *
     * @type {DrivesCreate400ResponseError}
     * @memberof DrivesCreate400Response
     */
    error: DrivesCreate400ResponseError;
}

/**
 * Check if a given object implements the DrivesCreate400Response interface.
 */
export function instanceOfDrivesCreate400Response(value: object): value is DrivesCreate400Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function DrivesCreate400ResponseFromJSON(json: any): DrivesCreate400Response {
    return DrivesCreate400ResponseFromJSONTyped(json, false);
}

export function DrivesCreate400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DrivesCreate400Response {
    if (json == null) {
        return json;
    }
    return {

        'error': DrivesCreate400ResponseErrorFromJSON(json['error']),
    };
}

export function DrivesCreate400ResponseToJSON(json: any): DrivesCreate400Response {
    return DrivesCreate400ResponseToJSONTyped(json, false);
}

export function DrivesCreate400ResponseToJSONTyped(value?: DrivesCreate400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'error': DrivesCreate400ResponseErrorToJSON(value['error']),
    };
}
