/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: <PINNED>
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PATCH /v0/drives/{id} body — rename a drive the caller owns.
 * @export
 * @interface DriveRenameIn
 */
export interface DriveRenameIn {
    /**
     *
     * @type {string}
     * @memberof DriveRenameIn
     */
    name: string;
}

/**
 * Check if a given object implements the DriveRenameIn interface.
 */
export function instanceOfDriveRenameIn(value: object): value is DriveRenameIn {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DriveRenameInFromJSON(json: any): DriveRenameIn {
    return DriveRenameInFromJSONTyped(json, false);
}

export function DriveRenameInFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriveRenameIn {
    if (json == null) {
        return json;
    }
    return {

        'name': json['name'],
    };
}

export function DriveRenameInToJSON(json: any): DriveRenameIn {
    return DriveRenameInToJSONTyped(json, false);
}

export function DriveRenameInToJSONTyped(value?: DriveRenameIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'name': value['name'],
    };
}
