/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DriveUsageOut
 */
export interface DriveUsageOut {
    /**
     * 
     */
    storageBytes: number;
    /**
     * 
     */
    retrievalBytes: number;
}

/**
 * Check if a given object implements the DriveUsageOut interface.
 */
export function instanceOfDriveUsageOut(value: object): value is DriveUsageOut {
    if ((!('storageBytes' in (value as Record<string, any>)) && !('storage_bytes' in (value as Record<string, any>))) || ((value as Record<string, any>)['storageBytes'] === undefined && (value as Record<string, any>)['storage_bytes'] === undefined)) return false;
    if ((!('retrievalBytes' in (value as Record<string, any>)) && !('retrieval_bytes' in (value as Record<string, any>))) || ((value as Record<string, any>)['retrievalBytes'] === undefined && (value as Record<string, any>)['retrieval_bytes'] === undefined)) return false;
    return true;
}

export function DriveUsageOutFromJSON(json: any): DriveUsageOut {
    return DriveUsageOutFromJSONTyped(json, false);
}

export function DriveUsageOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriveUsageOut {
    if (json == null) {
        return json;
    }
    return {
        
        'storageBytes': json['storage_bytes'],
        'retrievalBytes': json['retrieval_bytes'],
    };
}

export function DriveUsageOutToJSON(json: any): DriveUsageOut {
    return DriveUsageOutToJSONTyped(json, false);
}

export function DriveUsageOutToJSONTyped(value?: DriveUsageOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storage_bytes': value['storageBytes'],
        'retrieval_bytes': value['retrievalBytes'],
    };
}

