/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One drive in a listing — metadata only (workspaces-design §4.2).
 * Carries NO capability and NEVER a raw key. An admin's inventory and a
 * member's owned list both serialize to this shape; `owner_email` is the
 * only owner-identifying field surfaced.
 * @export
 * @interface DriveOut
 */
export interface DriveOut {
    /**
     * 
     * @type {string}
     * @memberof DriveOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DriveOut
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DriveOut
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof DriveOut
     */
    ownerUserId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DriveOut
     */
    ownerEmail?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DriveOut
     */
    storageBytes: number;
    /**
     * 
     * @type {Date}
     * @memberof DriveOut
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the DriveOut interface.
 */
export function instanceOfDriveOut(value: object): value is DriveOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('organizationId' in value) && !('organization_id' in value)) || (value['organizationId'] === undefined && value['organization_id'] === undefined)) return false;
    if ((!('storageBytes' in value) && !('storage_bytes' in value)) || (value['storageBytes'] === undefined && value['storage_bytes'] === undefined)) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    return true;
}

export function DriveOutFromJSON(json: any): DriveOut {
    return DriveOutFromJSONTyped(json, false);
}

export function DriveOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriveOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'organizationId': json['organization_id'],
        'ownerUserId': json['owner_user_id'] == null ? undefined : json['owner_user_id'],
        'ownerEmail': json['owner_email'] == null ? undefined : json['owner_email'],
        'storageBytes': json['storage_bytes'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function DriveOutToJSON(json: any): DriveOut {
    return DriveOutToJSONTyped(json, false);
}

export function DriveOutToJSONTyped(value?: DriveOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'owner_user_id': value['ownerUserId'],
        'owner_email': value['ownerEmail'],
        'storage_bytes': value['storageBytes'],
        'created_at': value['createdAt'].toISOString(),
    };
}

