/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: <PINNED>
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * `POST /v0/drives/{id}/keys` response — the new key's metadata PLUS the
 * raw `ad_live_` value, returned **once**. Store `api_key` now; only its hash
 * is persisted.
 * @export
 * @interface DriveApiKeyCreateOut
 */
export interface DriveApiKeyCreateOut {
    /**
     *
     * @type {string}
     * @memberof DriveApiKeyCreateOut
     */
    apiKey: string;
    /**
     *
     * @type {Date}
     * @memberof DriveApiKeyCreateOut
     */
    createdAt: Date;
    /**
     *
     * @type {string}
     * @memberof DriveApiKeyCreateOut
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof DriveApiKeyCreateOut
     */
    label?: string | null;
    /**
     *
     * @type {string}
     * @memberof DriveApiKeyCreateOut
     */
    prefix: string;
}

/**
 * Check if a given object implements the DriveApiKeyCreateOut interface.
 */
export function instanceOfDriveApiKeyCreateOut(value: object): value is DriveApiKeyCreateOut {
    if ((!('apiKey' in (value as Record<string, any>)) && !('api_key' in (value as Record<string, any>))) || ((value as Record<string, any>)['apiKey'] === undefined && (value as Record<string, any>)['api_key'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('prefix' in value) || value['prefix'] === undefined) return false;
    return true;
}

export function DriveApiKeyCreateOutFromJSON(json: any): DriveApiKeyCreateOut {
    return DriveApiKeyCreateOutFromJSONTyped(json, false);
}

export function DriveApiKeyCreateOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriveApiKeyCreateOut {
    if (json == null) {
        return json;
    }
    return {

        'apiKey': json['api_key'],
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'label': json['label'] === undefined ? undefined : json['label'] === null ? null : json['label'],
        'prefix': json['prefix'],
    };
}

export function DriveApiKeyCreateOutToJSON(json: any): DriveApiKeyCreateOut {
    return DriveApiKeyCreateOutToJSONTyped(json, false);
}

export function DriveApiKeyCreateOutToJSONTyped(value?: DriveApiKeyCreateOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'api_key': value['apiKey'],
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'label': value['label'],
        'prefix': value['prefix'],
    };
}
