/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: <PINNED>
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One passage-level hit from `/v0/find` (hybrid chunk RAG over
 * `embed_chunks`). The unit is a passage, not a file — consecutive
 * `ord` values from the same `art_id` are normal because chunks
 * overlap by ~400 tokens. Span fields are modality-aware: only the
 * pair matching `modality` is populated, the others stay None.
 * @export
 * @interface FindHitOut
 */
export interface FindHitOut {
    /**
     *
     * @type {string}
     * @memberof FindHitOut
     */
    artId: string;
    /**
     *
     * @type {number}
     * @memberof FindHitOut
     */
    charEnd?: number | null;
    /**
     *
     * @type {number}
     * @memberof FindHitOut
     */
    charStart?: number | null;
    /**
     *
     * @type {string}
     * @memberof FindHitOut
     */
    contentType: string;
    /**
     *
     * @type {string}
     * @memberof FindHitOut
     */
    driveId: string;
    /**
     *
     * @type {string}
     * @memberof FindHitOut
     */
    fileType: string;
    /**
     *
     * @type {Array<string>}
     * @memberof FindHitOut
     */
    labels?: Array<string>;
    /**
     *
     * @type {FindHitOutModalityEnum}
     * @memberof FindHitOut
     */
    modality: FindHitOutModalityEnum;
    /**
     *
     * @type {number}
     * @memberof FindHitOut
     */
    ord: number;
    /**
     *
     * @type {number}
     * @memberof FindHitOut
     */
    pageEnd?: number | null;
    /**
     *
     * @type {number}
     * @memberof FindHitOut
     */
    pageStart?: number | null;
    /**
     *
     * @type {string}
     * @memberof FindHitOut
     */
    path: string;
    /**
     *
     * @type {number}
     * @memberof FindHitOut
     */
    rankLexical?: number | null;
    /**
     *
     * @type {number}
     * @memberof FindHitOut
     */
    rankSemantic?: number | null;
    /**
     *
     * @type {number}
     * @memberof FindHitOut
     */
    score: number;
    /**
     *
     * @type {string}
     * @memberof FindHitOut
     */
    snippet: string;
    /**
     *
     * @type {string}
     * @memberof FindHitOut
     */
    text: string;
    /**
     *
     * @type {number}
     * @memberof FindHitOut
     */
    timeEndMs?: number | null;
    /**
     *
     * @type {number}
     * @memberof FindHitOut
     */
    timeStartMs?: number | null;
    /**
     *
     * @type {Date}
     * @memberof FindHitOut
     */
    updatedAt: Date;
    /**
     *
     * @type {string}
     * @memberof FindHitOut
     */
    url: string;
    /**
     *
     * @type {number}
     * @memberof FindHitOut
     */
    versionNumber: number;
}


/**
 * @export
 */
export const FindHitOutModalityEnum = {
    Text: 'text',
    Code: 'code',
    Pdf: 'pdf',
    Image: 'image',
    Audio: 'audio',
    Video: 'video'
} as const;
export type FindHitOutModalityEnum = typeof FindHitOutModalityEnum[keyof typeof FindHitOutModalityEnum];


/**
 * Check if a given object implements the FindHitOut interface.
 */
export function instanceOfFindHitOut(value: object): value is FindHitOut {
    if ((!('artId' in (value as Record<string, any>)) && !('art_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['artId'] === undefined && (value as Record<string, any>)['art_id'] === undefined)) return false;
    if ((!('contentType' in (value as Record<string, any>)) && !('content_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['contentType'] === undefined && (value as Record<string, any>)['content_type'] === undefined)) return false;
    if ((!('driveId' in (value as Record<string, any>)) && !('drive_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['driveId'] === undefined && (value as Record<string, any>)['drive_id'] === undefined)) return false;
    if ((!('fileType' in (value as Record<string, any>)) && !('file_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['fileType'] === undefined && (value as Record<string, any>)['file_type'] === undefined)) return false;
    if (!('modality' in value) || value['modality'] === undefined) return false;
    if (!('ord' in value) || value['ord'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('snippet' in value) || value['snippet'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if ((!('versionNumber' in (value as Record<string, any>)) && !('version_number' in (value as Record<string, any>))) || ((value as Record<string, any>)['versionNumber'] === undefined && (value as Record<string, any>)['version_number'] === undefined)) return false;
    return true;
}

export function FindHitOutFromJSON(json: any): FindHitOut {
    return FindHitOutFromJSONTyped(json, false);
}

export function FindHitOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindHitOut {
    if (json == null) {
        return json;
    }
    return {

        'artId': json['art_id'],
        'charEnd': json['char_end'] === undefined ? undefined : json['char_end'] === null ? null : json['char_end'],
        'charStart': json['char_start'] === undefined ? undefined : json['char_start'] === null ? null : json['char_start'],
        'contentType': json['content_type'],
        'driveId': json['drive_id'],
        'fileType': json['file_type'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'modality': json['modality'],
        'ord': json['ord'],
        'pageEnd': json['page_end'] === undefined ? undefined : json['page_end'] === null ? null : json['page_end'],
        'pageStart': json['page_start'] === undefined ? undefined : json['page_start'] === null ? null : json['page_start'],
        'path': json['path'],
        'rankLexical': json['rank_lexical'] === undefined ? undefined : json['rank_lexical'] === null ? null : json['rank_lexical'],
        'rankSemantic': json['rank_semantic'] === undefined ? undefined : json['rank_semantic'] === null ? null : json['rank_semantic'],
        'score': json['score'],
        'snippet': json['snippet'],
        'text': json['text'],
        'timeEndMs': json['time_end_ms'] === undefined ? undefined : json['time_end_ms'] === null ? null : json['time_end_ms'],
        'timeStartMs': json['time_start_ms'] === undefined ? undefined : json['time_start_ms'] === null ? null : json['time_start_ms'],
        'updatedAt': (new Date(json['updated_at'])),
        'url': json['url'],
        'versionNumber': json['version_number'],
    };
}

export function FindHitOutToJSON(json: any): FindHitOut {
    return FindHitOutToJSONTyped(json, false);
}

export function FindHitOutToJSONTyped(value?: FindHitOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'art_id': value['artId'],
        'char_end': value['charEnd'],
        'char_start': value['charStart'],
        'content_type': value['contentType'],
        'drive_id': value['driveId'],
        'file_type': value['fileType'],
        'labels': value['labels'],
        'modality': value['modality'],
        'ord': value['ord'],
        'page_end': value['pageEnd'],
        'page_start': value['pageStart'],
        'path': value['path'],
        'rank_lexical': value['rankLexical'],
        'rank_semantic': value['rankSemantic'],
        'score': value['score'],
        'snippet': value['snippet'],
        'text': value['text'],
        'time_end_ms': value['timeEndMs'],
        'time_start_ms': value['timeStartMs'],
        'updated_at': value['updatedAt'].toISOString(),
        'url': value['url'],
        'version_number': value['versionNumber'],
    };
}
