/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * POST /v0/folders/{fld_id}/copy body — duplicate the subtree to a
 * new path. `path` is the target folder path (canonical, trailing
 * slash). Its own schema (vs. reusing `FolderMoveIn`) keeps the copy
 * surface self-documenting in the OpenAPI spec.
 * @export
 * @interface FolderCopyIn
 */
export interface FolderCopyIn {
    /**
     * 
     * @type {string}
     * @memberof FolderCopyIn
     */
    path: string;
    /**
     * 
     * @type {number}
     * @memberof FolderCopyIn
     */
    fromMetageneration?: number | null;
}

/**
 * Check if a given object implements the FolderCopyIn interface.
 */
export function instanceOfFolderCopyIn(value: object): value is FolderCopyIn {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function FolderCopyInFromJSON(json: any): FolderCopyIn {
    return FolderCopyInFromJSONTyped(json, false);
}

export function FolderCopyInFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderCopyIn {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'fromMetageneration': json['from_metageneration'] === undefined ? undefined : json['from_metageneration'] === null ? null : json['from_metageneration'],
    };
}

export function FolderCopyInToJSON(json: any): FolderCopyIn {
    return FolderCopyInToJSONTyped(json, false);
}

export function FolderCopyInToJSONTyped(value?: FolderCopyIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'from_metageneration': value['fromMetageneration'],
    };
}

