/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FolderOut } from './FolderOut';
import {
    FolderOutFromJSON,
    FolderOutFromJSONTyped,
    FolderOutToJSON,
    FolderOutToJSONTyped,
} from './FolderOut';

/**
 * 
 * @export
 * @interface FolderCascadeOut
 */
export interface FolderCascadeOut {
    /**
     * 
     */
    folder: FolderOut;
    /**
     * 
     */
    cascade: { [key: string]: number; };
}

/**
 * Check if a given object implements the FolderCascadeOut interface.
 */
export function instanceOfFolderCascadeOut(value: object): value is FolderCascadeOut {
    if (!('folder' in value) || value['folder'] === undefined) return false;
    if (!('cascade' in value) || value['cascade'] === undefined) return false;
    return true;
}

export function FolderCascadeOutFromJSON(json: any): FolderCascadeOut {
    return FolderCascadeOutFromJSONTyped(json, false);
}

export function FolderCascadeOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderCascadeOut {
    if (json == null) {
        return json;
    }
    return {
        
        'folder': FolderOutFromJSON(json['folder']),
        'cascade': json['cascade'],
    };
}

export function FolderCascadeOutToJSON(json: any): FolderCascadeOut {
    return FolderCascadeOutToJSONTyped(json, false);
}

export function FolderCascadeOutToJSONTyped(value?: FolderCascadeOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'folder': FolderOutToJSON(value['folder']),
        'cascade': value['cascade'],
    };
}

