/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GrantOut } from './GrantOut';
import {
    GrantOutFromJSON,
    GrantOutFromJSONTyped,
    GrantOutToJSON,
    GrantOutToJSONTyped,
} from './GrantOut';

/**
 * 
 * @export
 * @interface GrantList
 */
export interface GrantList {
    /**
     * 
     * @type {Array<GrantOut>}
     * @memberof GrantList
     */
    items: Array<GrantOut>;
    /**
     * 
     * @type {string}
     * @memberof GrantList
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the GrantList interface.
 */
export function instanceOfGrantList(value: object): value is GrantList {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function GrantListFromJSON(json: any): GrantList {
    return GrantListFromJSONTyped(json, false);
}

export function GrantListFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrantList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GrantOutFromJSON)),
        'nextCursor': json['next_cursor'] === undefined ? undefined : json['next_cursor'] === null ? null : json['next_cursor'],
    };
}

export function GrantListToJSON(json: any): GrantList {
    return GrantListToJSONTyped(json, false);
}

export function GrantListToJSONTyped(value?: GrantList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(GrantOutToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

