/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectConfigIn
 */
export interface ProjectConfigIn {
    /**
     * 
     * @type {string}
     * @memberof ProjectConfigIn
     */
    entrypoint: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectConfigIn
     */
    engine?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectConfigIn
     */
    autoCompile?: boolean;
}

/**
 * Check if a given object implements the ProjectConfigIn interface.
 */
export function instanceOfProjectConfigIn(value: object): value is ProjectConfigIn {
    if (!('entrypoint' in value) || value['entrypoint'] === undefined) return false;
    return true;
}

export function ProjectConfigInFromJSON(json: any): ProjectConfigIn {
    return ProjectConfigInFromJSONTyped(json, false);
}

export function ProjectConfigInFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectConfigIn {
    if (json == null) {
        return json;
    }
    return {
        
        'entrypoint': json['entrypoint'],
        'engine': json['engine'] === undefined ? undefined : json['engine'] === null ? null : json['engine'],
        'autoCompile': json['auto_compile'] == null ? undefined : json['auto_compile'],
    };
}

export function ProjectConfigInToJSON(json: any): ProjectConfigIn {
    return ProjectConfigInToJSONTyped(json, false);
}

export function ProjectConfigInToJSONTyped(value?: ProjectConfigIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entrypoint': value['entrypoint'],
        'engine': value['engine'],
        'auto_compile': value['autoCompile'],
    };
}

