/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: <PINNED>
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShareOut } from './ShareOut';
import {
    ShareOutFromJSON,
    ShareOutFromJSONTyped,
    ShareOutToJSON,
    ShareOutToJSONTyped,
} from './ShareOut';

/**
 *
 * @export
 * @interface ShareListOut
 */
export interface ShareListOut {
    /**
     *
     * @type {Array<ShareOut>}
     * @memberof ShareListOut
     */
    items: Array<ShareOut>;
    /**
     *
     * @type {string}
     * @memberof ShareListOut
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the ShareListOut interface.
 */
export function instanceOfShareListOut(value: object): value is ShareListOut {
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('nextCursor' in (value as Record<string, any>)) && !('next_cursor' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextCursor'] === undefined && (value as Record<string, any>)['next_cursor'] === undefined)) return false;
    return true;
}

export function ShareListOutFromJSON(json: any): ShareListOut {
    return ShareListOutFromJSONTyped(json, false);
}

export function ShareListOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareListOut {
    if (json == null) {
        return json;
    }
    return {

        'items': ((json['items'] as Array<any>).map(ShareOutFromJSON)),
        'nextCursor': json['next_cursor'],
    };
}

export function ShareListOutToJSON(json: any): ShareListOut {
    return ShareListOutToJSONTyped(json, false);
}

export function ShareListOutToJSONTyped(value?: ShareListOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': ((value['items'] as Array<any>).map(ShareOutToJSON)),
        'next_cursor': value['nextCursor'],
    };
}
