/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: <PINNED>
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorBody } from './ErrorBody';
import {
    ErrorBodyFromJSON,
    ErrorBodyFromJSONTyped,
    ErrorBodyToJSON,
    ErrorBodyToJSONTyped,
} from './ErrorBody';

/**
 * Negotiated JSON error shape for the public share protocol.
 * @export
 * @interface ShareErrorOut
 */
export interface ShareErrorOut {
    /**
     *
     * @type {ErrorBody}
     * @memberof ShareErrorOut
     */
    error: ErrorBody;
}

/**
 * Check if a given object implements the ShareErrorOut interface.
 */
export function instanceOfShareErrorOut(value: object): value is ShareErrorOut {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ShareErrorOutFromJSON(json: any): ShareErrorOut {
    return ShareErrorOutFromJSONTyped(json, false);
}

export function ShareErrorOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareErrorOut {
    if (json == null) {
        return json;
    }
    return {

        'error': ErrorBodyFromJSON(json['error']),
    };
}

export function ShareErrorOutToJSON(json: any): ShareErrorOut {
    return ShareErrorOutToJSONTyped(json, false);
}

export function ShareErrorOutToJSONTyped(value?: ShareErrorOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'error': ErrorBodyToJSON(value['error']),
    };
}
