/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: <PINNED>
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The create/rotate response — the ONLY place the `share_key` and its
 * redemption `url` are exposed.
 * @export
 * @interface ShareMintOut
 */
export interface ShareMintOut {
    /**
     *
     * @type {number}
     * @memberof ShareMintOut
     */
    accessCount?: number;
    /**
     *
     * @type {string}
     * @memberof ShareMintOut
     */
    audience: string;
    /**
     *
     * @type {Date}
     * @memberof ShareMintOut
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof ShareMintOut
     */
    expiresAt?: Date | null;
    /**
     *
     * @type {boolean}
     * @memberof ShareMintOut
     */
    hasPassword: boolean;
    /**
     *
     * @type {string}
     * @memberof ShareMintOut
     */
    id: string;
    /**
     *
     * @type {Date}
     * @memberof ShareMintOut
     */
    lastAccessedAt?: Date | null;
    /**
     *
     * @type {string}
     * @memberof ShareMintOut
     */
    resourceId: string;
    /**
     *
     * @type {ShareMintOutResourceTypeEnum}
     * @memberof ShareMintOut
     */
    resourceType: ShareMintOutResourceTypeEnum;
    /**
     *
     * @type {ShareMintOutRoleEnum}
     * @memberof ShareMintOut
     */
    role: ShareMintOutRoleEnum;
    /**
     *
     * @type {string}
     * @memberof ShareMintOut
     */
    shareKey: string;
    /**
     *
     * @type {string}
     * @memberof ShareMintOut
     */
    url: string;
}


/**
 * @export
 */
export const ShareMintOutResourceTypeEnum = {
    Artifact: 'artifact',
    Folder: 'folder'
} as const;
export type ShareMintOutResourceTypeEnum = typeof ShareMintOutResourceTypeEnum[keyof typeof ShareMintOutResourceTypeEnum];

/**
 * @export
 */
export const ShareMintOutRoleEnum = {
    Viewer: 'viewer',
    Commenter: 'commenter',
    Editor: 'editor'
} as const;
export type ShareMintOutRoleEnum = typeof ShareMintOutRoleEnum[keyof typeof ShareMintOutRoleEnum];


/**
 * Check if a given object implements the ShareMintOut interface.
 */
export function instanceOfShareMintOut(value: object): value is ShareMintOut {
    if (!('audience' in value) || value['audience'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('hasPassword' in (value as Record<string, any>)) && !('has_password' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasPassword'] === undefined && (value as Record<string, any>)['has_password'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('resourceId' in (value as Record<string, any>)) && !('resource_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['resourceId'] === undefined && (value as Record<string, any>)['resource_id'] === undefined)) return false;
    if ((!('resourceType' in (value as Record<string, any>)) && !('resource_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['resourceType'] === undefined && (value as Record<string, any>)['resource_type'] === undefined)) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if ((!('shareKey' in (value as Record<string, any>)) && !('share_key' in (value as Record<string, any>))) || ((value as Record<string, any>)['shareKey'] === undefined && (value as Record<string, any>)['share_key'] === undefined)) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ShareMintOutFromJSON(json: any): ShareMintOut {
    return ShareMintOutFromJSONTyped(json, false);
}

export function ShareMintOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareMintOut {
    if (json == null) {
        return json;
    }
    return {

        'accessCount': json['access_count'] == null ? undefined : json['access_count'],
        'audience': json['audience'],
        'createdAt': (new Date(json['created_at'])),
        'expiresAt': json['expires_at'] === undefined ? undefined : json['expires_at'] === null ? null : (new Date(json['expires_at'])),
        'hasPassword': json['has_password'],
        'id': json['id'],
        'lastAccessedAt': json['last_accessed_at'] === undefined ? undefined : json['last_accessed_at'] === null ? null : (new Date(json['last_accessed_at'])),
        'resourceId': json['resource_id'],
        'resourceType': json['resource_type'],
        'role': json['role'],
        'shareKey': json['share_key'],
        'url': json['url'],
    };
}

export function ShareMintOutToJSON(json: any): ShareMintOut {
    return ShareMintOutToJSONTyped(json, false);
}

export function ShareMintOutToJSONTyped(value?: ShareMintOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'access_count': value['accessCount'],
        'audience': value['audience'],
        'created_at': value['createdAt'].toISOString(),
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'has_password': value['hasPassword'],
        'id': value['id'],
        'last_accessed_at': value['lastAccessedAt'] == null ? value['lastAccessedAt'] : value['lastAccessedAt'].toISOString(),
        'resource_id': value['resourceId'],
        'resource_type': value['resourceType'],
        'role': value['role'],
        'share_key': value['shareKey'],
        'url': value['url'],
    };
}
