/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface ShareOut
 */
export interface ShareOut {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    driveId: string;
    /**
     * 
     */
    resourceType: ShareOutResourceTypeEnum;
    /**
     * 
     */
    resourceId: string;
    /**
     * 
     */
    createdBy: string | null;
    /**
     * 
     */
    revision: string;
    /**
     * 
     */
    state: ShareOutStateEnum;
    /**
     * 
     */
    expiresAt: Date | null;
    /**
     * 
     */
    revokedAt: Date | null;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    rotatedAt: Date | null;
}


/**
 * @export
 */
export const ShareOutResourceTypeEnum = {
    Artifact: 'artifact',
    ArtifactVersion: 'artifact_version',
    Folder: 'folder',
} as const;
export type ShareOutResourceTypeEnum = typeof ShareOutResourceTypeEnum[keyof typeof ShareOutResourceTypeEnum];

/**
 * @export
 */
export const ShareOutStateEnum = {
    Active: 'active',
    Revoked: 'revoked',
    Expired: 'expired',
} as const;
export type ShareOutStateEnum = typeof ShareOutStateEnum[keyof typeof ShareOutStateEnum];


/**
 * Check if a given object implements the ShareOut interface.
 */
export function instanceOfShareOut(value: object): value is ShareOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('driveId' in (value as Record<string, any>)) && !('drive_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['driveId'] === undefined && (value as Record<string, any>)['drive_id'] === undefined)) return false;
    if ((!('resourceType' in (value as Record<string, any>)) && !('resource_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['resourceType'] === undefined && (value as Record<string, any>)['resource_type'] === undefined)) return false;
    if ((!('resourceId' in (value as Record<string, any>)) && !('resource_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['resourceId'] === undefined && (value as Record<string, any>)['resource_id'] === undefined)) return false;
    if ((!('createdBy' in (value as Record<string, any>)) && !('created_by' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdBy'] === undefined && (value as Record<string, any>)['created_by'] === undefined)) return false;
    if (!('revision' in value) || value['revision'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if ((!('expiresAt' in (value as Record<string, any>)) && !('expires_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['expiresAt'] === undefined && (value as Record<string, any>)['expires_at'] === undefined)) return false;
    if ((!('revokedAt' in (value as Record<string, any>)) && !('revoked_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['revokedAt'] === undefined && (value as Record<string, any>)['revoked_at'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('rotatedAt' in (value as Record<string, any>)) && !('rotated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['rotatedAt'] === undefined && (value as Record<string, any>)['rotated_at'] === undefined)) return false;
    return true;
}

export function ShareOutFromJSON(json: any): ShareOut {
    return ShareOutFromJSONTyped(json, false);
}

export function ShareOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'driveId': json['drive_id'],
        'resourceType': json['resource_type'],
        'resourceId': json['resource_id'],
        'createdBy': json['created_by'],
        'revision': json['revision'],
        'state': json['state'],
        'expiresAt': (json['expires_at'] == null ? null : parseDateTime(json['expires_at'])),
        'revokedAt': (json['revoked_at'] == null ? null : parseDateTime(json['revoked_at'])),
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'rotatedAt': (json['rotated_at'] == null ? null : parseDateTime(json['rotated_at'])),
    };
}

export function ShareOutToJSON(json: any): ShareOut {
    return ShareOutToJSONTyped(json, false);
}

export function ShareOutToJSONTyped(value?: ShareOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'drive_id': value['driveId'],
        'resource_type': value['resourceType'],
        'resource_id': value['resourceId'],
        'created_by': value['createdBy'],
        'revision': value['revision'],
        'state': value['state'],
        'expires_at': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
        'revoked_at': value['revokedAt'] == null ? value['revokedAt'] : serializeDateTime(value['revokedAt']),
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'rotated_at': value['rotatedAt'] == null ? value['rotatedAt'] : serializeDateTime(value['rotatedAt']),
    };
}

