/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One typed provenance ref. `type` is open-vocabulary (server
 * validates only length, not the value), so callers can declare new
 * types as their integrations evolve. `id` is the type-specific
 * identifier — for `type='artifact'` this is an `art_…` ID.
 * @export
 * @interface SourceRef
 */
export interface SourceRef {
    /**
     * 
     * @type {string}
     * @memberof SourceRef
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof SourceRef
     */
    id: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SourceRef
     */
    metadata?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the SourceRef interface.
 */
export function instanceOfSourceRef(value: object): value is SourceRef {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SourceRefFromJSON(json: any): SourceRef {
    return SourceRefFromJSONTyped(json, false);
}

export function SourceRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceRef {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'metadata': json['metadata'] === undefined ? undefined : json['metadata'] === null ? null : json['metadata'],
    };
}

export function SourceRefToJSON(json: any): SourceRef {
    return SourceRefToJSONTyped(json, false);
}

export function SourceRefToJSONTyped(value?: SourceRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'metadata': value['metadata'],
    };
}

