/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { UploadTargetArtifactOut } from './UploadTargetArtifactOut';
import {
    instanceOfUploadTargetArtifactOut,
    UploadTargetArtifactOutFromJSON,
    UploadTargetArtifactOutFromJSONTyped,
    UploadTargetArtifactOutToJSON,
} from './UploadTargetArtifactOut';
import type { UploadTargetVersionOut } from './UploadTargetVersionOut';
import {
    instanceOfUploadTargetVersionOut,
    UploadTargetVersionOutFromJSON,
    UploadTargetVersionOutFromJSONTyped,
    UploadTargetVersionOutToJSON,
} from './UploadTargetVersionOut';

/**
 * @type Target
 * 
 * @export
 */
export type Target = { kind: 'artifact' } & UploadTargetArtifactOut | { kind: 'version' } & UploadTargetVersionOut;

export function TargetFromJSON(json: any): Target {
    return TargetFromJSONTyped(json, false);
}

export function TargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Target {
    if (json == null) {
        return json;
    }
    switch (json['kind']) {
        case 'artifact':
            return Object.assign({}, UploadTargetArtifactOutFromJSONTyped(json, true), { kind: 'artifact' } as const);
        case 'version':
            return Object.assign({}, UploadTargetVersionOutFromJSONTyped(json, true), { kind: 'version' } as const);
        default:
            return json;
    }
}

export function TargetToJSON(json: any): any {
    return TargetToJSONTyped(json, false);
}

export function TargetToJSONTyped(value?: Target | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['kind']) {
        case 'artifact':
            return Object.assign({}, UploadTargetArtifactOutToJSON(value), { 'kind': 'artifact' } as const);
        case 'version':
            return Object.assign({}, UploadTargetVersionOutToJSON(value), { 'kind': 'version' } as const);
        default:
            return value;
    }
}

