/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: <PINNED>
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrashDriveOut } from './TrashDriveOut';
import {
    TrashDriveOutFromJSON,
    TrashDriveOutFromJSONTyped,
    TrashDriveOutToJSON,
    TrashDriveOutToJSONTyped,
} from './TrashDriveOut';
import type { TrashArtifactOut } from './TrashArtifactOut';
import {
    TrashArtifactOutFromJSON,
    TrashArtifactOutFromJSONTyped,
    TrashArtifactOutToJSON,
    TrashArtifactOutToJSONTyped,
} from './TrashArtifactOut';

/**
 * Trash collection with a compatibility-preserving pagination opt-in.
 * @export
 * @interface TrashOut
 */
export interface TrashOut {
    /**
     * Deprecated alias of items.
     * @type {Array<TrashArtifactOut>}
     * @memberof TrashOut
     * @deprecated
     */
    artifacts: Array<TrashArtifactOut>;
    /**
     *
     * @type {TrashDriveOut}
     * @memberof TrashOut
     */
    drive: TrashDriveOut;
    /**
     *
     * @type {Array<TrashArtifactOut>}
     * @memberof TrashOut
     */
    items: Array<TrashArtifactOut>;
    /**
     *
     * @type {string}
     * @memberof TrashOut
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the TrashOut interface.
 */
export function instanceOfTrashOut(value: object): value is TrashOut {
    if (!('artifacts' in value) || value['artifacts'] === undefined) return false;
    if (!('drive' in value) || value['drive'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function TrashOutFromJSON(json: any): TrashOut {
    return TrashOutFromJSONTyped(json, false);
}

export function TrashOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrashOut {
    if (json == null) {
        return json;
    }
    return {

        'artifacts': ((json['artifacts'] as Array<any>).map(TrashArtifactOutFromJSON)),
        'drive': TrashDriveOutFromJSON(json['drive']),
        'items': ((json['items'] as Array<any>).map(TrashArtifactOutFromJSON)),
        'nextCursor': json['next_cursor'] === undefined ? undefined : json['next_cursor'] === null ? null : json['next_cursor'],
    };
}

export function TrashOutToJSON(json: any): TrashOut {
    return TrashOutToJSONTyped(json, false);
}

export function TrashOutToJSONTyped(value?: TrashOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'artifacts': ((value['artifacts'] as Array<any>).map(TrashArtifactOutToJSON)),
        'drive': TrashDriveOutToJSON(value['drive']),
        'items': ((value['items'] as Array<any>).map(TrashArtifactOutToJSON)),
        'next_cursor': value['nextCursor'],
    };
}
