/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: <PINNED>
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UploadTargetArtifactOut
 */
export interface UploadTargetArtifactOut {
    /**
     *
     * @type {string}
     * @memberof UploadTargetArtifactOut
     */
    kind: UploadTargetArtifactOutKindEnum;
    /**
     *
     * @type {string}
     * @memberof UploadTargetArtifactOut
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof UploadTargetArtifactOut
     */
    parentFolderId: string;
}


/**
 * @export
 */
export const UploadTargetArtifactOutKindEnum = {
    Artifact: 'artifact'
} as const;
export type UploadTargetArtifactOutKindEnum = typeof UploadTargetArtifactOutKindEnum[keyof typeof UploadTargetArtifactOutKindEnum];


/**
 * Check if a given object implements the UploadTargetArtifactOut interface.
 */
export function instanceOfUploadTargetArtifactOut(value: object): value is UploadTargetArtifactOut {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('parentFolderId' in value) || value['parentFolderId'] === undefined) return false;
    return true;
}

export function UploadTargetArtifactOutFromJSON(json: any): UploadTargetArtifactOut {
    return UploadTargetArtifactOutFromJSONTyped(json, false);
}

export function UploadTargetArtifactOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadTargetArtifactOut {
    if (json == null) {
        return json;
    }
    return {

        'kind': json['kind'],
        'name': json['name'],
        'parentFolderId': json['parent_folder_id'],
    };
}

export function UploadTargetArtifactOutToJSON(json: any): UploadTargetArtifactOut {
    return UploadTargetArtifactOutToJSONTyped(json, false);
}

export function UploadTargetArtifactOutToJSONTyped(value?: UploadTargetArtifactOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'kind': value['kind'],
        'name': value['name'],
        'parent_folder_id': value['parentFolderId'],
    };
}
