/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadsCreateRequestTargetOneOf1
 */
export interface UploadsCreateRequestTargetOneOf1 {
    /**
     * 
     */
    kind: UploadsCreateRequestTargetOneOf1KindEnum;
    /**
     * 
     */
    artifactId: string;
}


/**
 * @export
 */
export const UploadsCreateRequestTargetOneOf1KindEnum = {
    Version: 'version',
} as const;
export type UploadsCreateRequestTargetOneOf1KindEnum = typeof UploadsCreateRequestTargetOneOf1KindEnum[keyof typeof UploadsCreateRequestTargetOneOf1KindEnum];


/**
 * Check if a given object implements the UploadsCreateRequestTargetOneOf1 interface.
 */
export function instanceOfUploadsCreateRequestTargetOneOf1(value: object): value is UploadsCreateRequestTargetOneOf1 {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (value['kind'] !== 'version') return false;
    
    if ((!('artifactId' in (value as Record<string, any>)) && !('artifact_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['artifactId'] === undefined && (value as Record<string, any>)['artifact_id'] === undefined)) return false;
    return true;
}

export function UploadsCreateRequestTargetOneOf1FromJSON(json: any): UploadsCreateRequestTargetOneOf1 {
    return UploadsCreateRequestTargetOneOf1FromJSONTyped(json, false);
}

export function UploadsCreateRequestTargetOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadsCreateRequestTargetOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'artifactId': json['artifact_id'],
    };
}

export function UploadsCreateRequestTargetOneOf1ToJSON(json: any): UploadsCreateRequestTargetOneOf1 {
    return UploadsCreateRequestTargetOneOf1ToJSONTyped(json, false);
}

export function UploadsCreateRequestTargetOneOf1ToJSONTyped(value?: UploadsCreateRequestTargetOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'artifact_id': value['artifactId'],
    };
}

