/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadChecksumOut } from './UploadChecksumOut';
import {
    UploadChecksumOutFromJSON,
    UploadChecksumOutFromJSONTyped,
    UploadChecksumOutToJSON,
    UploadChecksumOutToJSONTyped,
} from './UploadChecksumOut';

/**
 * 
 * @export
 * @interface UploadContentOut
 */
export interface UploadContentOut {
    /**
     * 
     */
    sizeBytes: number;
    /**
     * 
     */
    mediaType: string;
    /**
     * 
     */
    checksum: UploadChecksumOut;
}

/**
 * Check if a given object implements the UploadContentOut interface.
 */
export function instanceOfUploadContentOut(value: object): value is UploadContentOut {
    if ((!('sizeBytes' in (value as Record<string, any>)) && !('size_bytes' in (value as Record<string, any>))) || ((value as Record<string, any>)['sizeBytes'] === undefined && (value as Record<string, any>)['size_bytes'] === undefined)) return false;
    if ((!('mediaType' in (value as Record<string, any>)) && !('media_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['mediaType'] === undefined && (value as Record<string, any>)['media_type'] === undefined)) return false;
    if (!('checksum' in value) || value['checksum'] === undefined) return false;
    return true;
}

export function UploadContentOutFromJSON(json: any): UploadContentOut {
    return UploadContentOutFromJSONTyped(json, false);
}

export function UploadContentOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadContentOut {
    if (json == null) {
        return json;
    }
    return {
        
        'sizeBytes': json['size_bytes'],
        'mediaType': json['media_type'],
        'checksum': UploadChecksumOutFromJSON(json['checksum']),
    };
}

export function UploadContentOutToJSON(json: any): UploadContentOut {
    return UploadContentOutToJSONTyped(json, false);
}

export function UploadContentOutToJSONTyped(value?: UploadContentOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size_bytes': value['sizeBytes'],
        'media_type': value['mediaType'],
        'checksum': UploadChecksumOutToJSON(value['checksum']),
    };
}

