/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: <PINNED>
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface VersionOut
 */
export interface VersionOut {
    /**
     *
     * @type {string}
     * @memberof VersionOut
     */
    actorName?: string | null;
    /**
     *
     * @type {string}
     * @memberof VersionOut
     */
    artId: string;
    /**
     *
     * @type {string}
     * @memberof VersionOut
     */
    changeSummary?: string | null;
    /**
     *
     * @type {string}
     * @memberof VersionOut
     */
    contentType: string;
    /**
     *
     * @type {Date}
     * @memberof VersionOut
     */
    createdAt: Date;
    /**
     *
     * @type {string}
     * @memberof VersionOut
     */
    hash: string;
    /**
     *
     * @type {number}
     * @memberof VersionOut
     */
    sizeBytes: number;
    /**
     *
     * @type {number}
     * @memberof VersionOut
     */
    versionNumber: number;
}

/**
 * Check if a given object implements the VersionOut interface.
 */
export function instanceOfVersionOut(value: object): value is VersionOut {
    if ((!('artId' in (value as Record<string, any>)) && !('art_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['artId'] === undefined && (value as Record<string, any>)['art_id'] === undefined)) return false;
    if ((!('contentType' in (value as Record<string, any>)) && !('content_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['contentType'] === undefined && (value as Record<string, any>)['content_type'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if ((!('sizeBytes' in (value as Record<string, any>)) && !('size_bytes' in (value as Record<string, any>))) || ((value as Record<string, any>)['sizeBytes'] === undefined && (value as Record<string, any>)['size_bytes'] === undefined)) return false;
    if ((!('versionNumber' in (value as Record<string, any>)) && !('version_number' in (value as Record<string, any>))) || ((value as Record<string, any>)['versionNumber'] === undefined && (value as Record<string, any>)['version_number'] === undefined)) return false;
    return true;
}

export function VersionOutFromJSON(json: any): VersionOut {
    return VersionOutFromJSONTyped(json, false);
}

export function VersionOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionOut {
    if (json == null) {
        return json;
    }
    return {

        'actorName': json['actor_name'] === undefined ? undefined : json['actor_name'] === null ? null : json['actor_name'],
        'artId': json['art_id'],
        'changeSummary': json['change_summary'] === undefined ? undefined : json['change_summary'] === null ? null : json['change_summary'],
        'contentType': json['content_type'],
        'createdAt': (new Date(json['created_at'])),
        'hash': json['hash'],
        'sizeBytes': json['size_bytes'],
        'versionNumber': json['version_number'],
    };
}

export function VersionOutToJSON(json: any): VersionOut {
    return VersionOutToJSONTyped(json, false);
}

export function VersionOutToJSONTyped(value?: VersionOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'actor_name': value['actorName'],
        'art_id': value['artId'],
        'change_summary': value['changeSummary'],
        'content_type': value['contentType'],
        'created_at': value['createdAt'].toISOString(),
        'hash': value['hash'],
        'size_bytes': value['sizeBytes'],
        'version_number': value['versionNumber'],
    };
}
