/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: drive-scoped folders, artifacts, and immutable versions, with local grants, possession-based share links, drive-scoped search, and a cursor-resumable change feed. Bearer-authenticated with Hub-issued product tokens (see /.well-known/oauth-protected-resource); every mutation takes an Idempotency-Key, and existing-state mutations take If-Match.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface VersionOut
 */
export interface VersionOut {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    artifactId: string;
    /**
     * 
     */
    versionNumber: number;
    /**
     * 
     */
    parentVersionId: string | null;
    /**
     * 
     */
    contentType: string;
    /**
     * 
     */
    sizeBytes: number;
    /**
     * 
     */
    hash: string;
    /**
     * 
     */
    createdBy: string | null;
    /**
     * 
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the VersionOut interface.
 */
export function instanceOfVersionOut(value: object): value is VersionOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('artifactId' in (value as Record<string, any>)) && !('artifact_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['artifactId'] === undefined && (value as Record<string, any>)['artifact_id'] === undefined)) return false;
    if ((!('versionNumber' in (value as Record<string, any>)) && !('version_number' in (value as Record<string, any>))) || ((value as Record<string, any>)['versionNumber'] === undefined && (value as Record<string, any>)['version_number'] === undefined)) return false;
    if ((!('parentVersionId' in (value as Record<string, any>)) && !('parent_version_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['parentVersionId'] === undefined && (value as Record<string, any>)['parent_version_id'] === undefined)) return false;
    if ((!('contentType' in (value as Record<string, any>)) && !('content_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['contentType'] === undefined && (value as Record<string, any>)['content_type'] === undefined)) return false;
    if ((!('sizeBytes' in (value as Record<string, any>)) && !('size_bytes' in (value as Record<string, any>))) || ((value as Record<string, any>)['sizeBytes'] === undefined && (value as Record<string, any>)['size_bytes'] === undefined)) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if ((!('createdBy' in (value as Record<string, any>)) && !('created_by' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdBy'] === undefined && (value as Record<string, any>)['created_by'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    return true;
}

export function VersionOutFromJSON(json: any): VersionOut {
    return VersionOutFromJSONTyped(json, false);
}

export function VersionOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'artifactId': json['artifact_id'],
        'versionNumber': json['version_number'],
        'parentVersionId': json['parent_version_id'],
        'contentType': json['content_type'],
        'sizeBytes': json['size_bytes'],
        'hash': json['hash'],
        'createdBy': json['created_by'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
    };
}

export function VersionOutToJSON(json: any): VersionOut {
    return VersionOutToJSONTyped(json, false);
}

export function VersionOutToJSONTyped(value?: VersionOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'artifact_id': value['artifactId'],
        'version_number': value['versionNumber'],
        'parent_version_id': value['parentVersionId'],
        'content_type': value['contentType'],
        'size_bytes': value['sizeBytes'],
        'hash': value['hash'],
        'created_by': value['createdBy'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

