/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceOut } from './WorkspaceOut';
import {
    WorkspaceOutFromJSON,
    WorkspaceOutFromJSONTyped,
    WorkspaceOutToJSON,
    WorkspaceOutToJSONTyped,
} from './WorkspaceOut';

/**
 * 
 * @export
 * @interface WorkspaceList
 */
export interface WorkspaceList {
    /**
     * 
     * @type {Array<WorkspaceOut>}
     * @memberof WorkspaceList
     */
    items: Array<WorkspaceOut>;
    /**
     * 
     * @type {string}
     * @memberof WorkspaceList
     */
    nextCursor?: string | null;
}

/**
 * Check if a given object implements the WorkspaceList interface.
 */
export function instanceOfWorkspaceList(value: object): value is WorkspaceList {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function WorkspaceListFromJSON(json: any): WorkspaceList {
    return WorkspaceListFromJSONTyped(json, false);
}

export function WorkspaceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WorkspaceOutFromJSON)),
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function WorkspaceListToJSON(json: any): WorkspaceList {
    return WorkspaceListToJSONTyped(json, false);
}

export function WorkspaceListToJSONTyped(value?: WorkspaceList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WorkspaceOutToJSON)),
        'next_cursor': value['nextCursor'],
    };
}

