/*
AgentDrive

Testing SharesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agentdrive

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/tokencanopy/agentdrive-sdk/agentdrive"
)

func Test_agentdrive_SharesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SharesAPIService SharesCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var driveId string

		resp, httpRes, err := apiClient.SharesAPI.SharesCreate(context.Background(), driveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SharesAPIService SharesList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var driveId string

		resp, httpRes, err := apiClient.SharesAPI.SharesList(context.Background(), driveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SharesAPIService SharesRead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var driveId string
		var shareId string

		resp, httpRes, err := apiClient.SharesAPI.SharesRead(context.Background(), driveId, shareId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SharesAPIService SharesRevoke", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var driveId string
		var shareId string

		resp, httpRes, err := apiClient.SharesAPI.SharesRevoke(context.Background(), driveId, shareId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SharesAPIService SharesRotate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var driveId string
		var shareId string

		resp, httpRes, err := apiClient.SharesAPI.SharesRotate(context.Background(), driveId, shareId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
